### ISSUE TITLE
JSXFragment / jsx-dom-expressions 

### ISSUE THREAD

**Issue by iamjohnlong** [ryansolid/solid#1]
I'm trying to set up a codesandbox to play around with solid. 

I'm getting

`You gave us a visitor for the node type "JSXFragment" but it's not a valid type`

https://codesandbox.io/s/rwvlplp084

Can you help get a template/sandbox working? Thanks!

**Comment by ryansolid** [comment]
I've seen this error before on older versions of Babel. Pre Babel 7 JSX  Fragment elements weren't supported. I haven't used codesandbox before but looking at dependencies I don't see where Babel is being imported. I suspect it is using Babel 6 or even one of the earlier versions of 7 beta. I developed this on the beta. However version 7 was released 10 days ago. It's possible 3rd party software hasn't updated to 7 yet.

If explicitly setting the babel dependencies is an option I imagine that should get past this. I probably should add this to the Readme.

**Comment by iamjohnlong** [comment]
Yeah I thought it could be a babel version issue. I will stop being lazy and set it up locally and let you know if I have the same issue.

**Comment by ryansolid** [comment]
Hmm.. I haven't seen that in my projects. Maybe because there is no reference in the initial build it's being skipped by webpack but I use Webpack 4 as well. I wouldn't expect needing to set it on window. I wonder if any reference would keep it in scope. I will take a look when I have some time to see if I can puzzle why it happens.
