### ISSUE TITLE
<For> index not updating on array shrink

### ISSUE THREAD

**Issue by boogerlad** [ryansolid/solid#106]
https://codesandbox.io/s/solid-simple-todos-puw2j
Add three todos. Remove the second one. Notice how the indices are now 0 and 2, when it should be 0 and 1.

I've traced the issue down to here: https://github.com/ryansolid/solid/blob/master/src/operator.ts#L177
and have fixed it like so.

```
 if (start > newEnd) {
-	for (j = end; start <= j; j--) disposers[j]();
+	for (j = end; j >= 0; j--) disposers[j]();
 	const rLen = end - start + 1;
 	if (rLen > 0) {
 		mapped.splice(start, rLen);
 		disposers.splice(start, rLen);
 	}
+	for (j = 0; j < newLen; j++) {
+		items[j] = newItems[j];
+		mapped[j] = createRoot(mapper);
+	}
 	items = newItems.slice(0);
 	len = newLen;
 	return mapped;
```

However, I'm pretty sure this is not optimal in terms of performance. Please offer guidance on the proper way to fix this so I can open up a PR, or you can fix it, or close this issue if it's actually working as intended.

Thank you.

**Comment by ryansolid** [comment]
Yeah this is actually working as intended as in the index itself isn't a signal, it's not reactive so the space around it is inert. You wouldn't want to re-render everything after an index on removal. It's expensive as it creates actual DOM nodes. I have had this question come up before. I wrote a simple control flow to handle it. See `ForIndex` in this example: https://codesandbox.io/s/list-indices-w3vlv. It maps the index to a signal so that it can update dynamically.

There was some talk about whether this should be core or not. It does have a little bit of overhead to use as the main method. We talked about removing the index from the signature to remove confusion (see https://github.com/ryansolid/solid/issues/51). It might also be possible at the cost of code size to have it opt in based on the arity of the handler function. I'd love to have your thoughts.

**Comment by boogerlad** [comment]
Ah that makes sense! I figured updating it was expensive. `ForIndex` does the job. Unfortunately my previous search through GitHub issues didn't yield any results, so sorry for cluttering up the issue tracker. If it were up to me, I'd remove the index from the current `For` and have `ForIndex` as a separate directive. I can't think of any cases where a static index would be useful. Using a dynamic index, if never updated, the only cost would be memory usage and initial render time correct?

My original use case for the index was to use it for splicing an array in `state` instead of using filter, a loop or some other `O(n)` solution. It seems that using `ForIndex` is just as expensive if not more though, am I correct?

**Comment by ryansolid** [comment]
> Using a dynamic index, if never updated, the only cost would be memory usage and initial render time correct?

Yes, although any list editing(unshift, swap, sort, etc..) would cause an index update so a little bit of an execution overhead. It fires the other effect to synchronize the indexes.

Yeah the cost of updating the synchronization would be more than using an optimized lookup. I tried a lot of different things when working on the JS Framework Benchmark. Using a `clone` and `findIndex` or `indexOf` and a `splice` is the fastest even though it involves iterating over the list a few times technically. `filter` is actually pretty close in performance up to a certain length probably because it clones in a single step but these helpers ended up being faster than any iterative methods. Now I could probably make a better approach to updating the index (I did at some point in the past) but I wouldn't expect that to improve row removals in comparison to the overhead. Mind you I'm sure that changes if the name of the game is to remove multiple rows in quick succession.

In any case, I agree about the static index. I will iterate over some more options when I'm in a good place to benchmark again (probably on the next minor version 0.15.0).
