### ISSUE TITLE
Runaway clock detected with StyledComponents and lazy children

### ISSUE THREAD

**Issue by r0skar** [ryansolid/solid#115]
Hi, I ran into an issue with styled components (based on the Codepen demo). It seems that using lazy children does not work, except when its the only child.

I have forked the Codepen: https://codesandbox.io/s/solid-emotion-psw9k

It works fine as long as `LazyChild` is the only child. Once I add another child (doesnt matter whether lazy or not), it breaks.

**Comment by ryansolid** [comment]
Ha. You got on this one quick. I was just playing with adding Component support last night in that sandbox. I forgot I had linked it. In any case its interesting and might signify a more general issue. Thanks for reporting.

**Comment by ryansolid** [comment]
Yeah this is a big one. Styled components use of `props.children` (through the spread) in conjunction with `createResource` is what brought this to light but it could happen in a number of other ways.

The combination of lazy evaluated props with fragments that return dynamic expressions that get read in the same context can cause infinite loops. It hasn't happened to this point because we just haven't had the right catalyst (in this case `createResource`) but this issue has been potentially present since the control flow refactor in version 0.9.0. It's an edge of edge cases but fixing `createResource` is insufficient. I need to tweak the core runtime to stop other similar issues from surfacing in the future. I imagine I will be working on this for the next several days. So I thank you ahead for your patience.

**Comment by ryansolid** [comment]
Ok I've fixed this now in v0.16.2. It requires updating babel-preset-solid to the latest as well as this was change to the DOM Expression and the Babel Plugin. Now handles array normalization in layers, the way it handles individual accessors. A bit of an "inception" sort of scenario but this approach has proven to work. I originally thought I could flatten all resolutions but that can create infinite loops.
