### ISSUE TITLE
Could you go to detail about how to use Refs?

### ISSUE THREAD

**Issue by Seanmclem** [ryansolid/solid#116]
Found something in the jsx rendering documentation mentioning Refs but no detail like I might expect.  if I'm just not finding it please let me know

**Comment by ryansolid** [comment]
For sure. There is a bit more on the babel plugin repo but not much.

Right now there are 2 types of refs and they need different syntax since they are handled by the compiler. I originally wanted refs to be really simple but I sometimes question its usefulness given how reactivity generally works.

## `ref`
```jsx
function MyComp() {
  let myDiv;
  setTimeout(() => console.log(myDiv.clientWidth));
  return <div ref={myDiv} />
}
```
On a native intrinsic element as the element executes the provided variable will be assigned. This form usually is used in combination with `setTimeout` (same timing as React's `useEffect`) or `afterEffects`(same timing as React's `useLayoutEffect`) to do work after the component has mounted. Like do a DOM measurement or attach DOM plugins etc...

When applied to a Component it acts similarly but also passes a prop in that is a function that is expected to be called with a ref to forward the ref (more on this in the next section):
```jsx
function App() {
  let myDiv;
  setTimeout(() => console.log(myDiv.clientWidth));
  return <MyComp ref={myDiv} />
}
``` 

## `forwardRef`
This form expects a function like React's callback refs. Original use case is like described above:
```jsx
function MyComp(props) {
  return <div forwardRef={props.ref} />
}

function App() {
  let myDiv;
  setTimeout(() => console.log(myDiv.clientWidth));
  return <MyComp ref={myDiv} />
}
```
You can also apply `forwardRef` on a Component:
```jsx
function App() {
  return <MyComp forwardRef={ref => console.log(ref.clientWidth)} />
}
```
This just passes the function through as `props.ref` again and work similar to the example above except it would run synchronously during render. You can use this to chain as many `forwardRef` up a Component chain as you wish.

The other use of `forwardRef` is to do custom binding. Since they run synchronously, computations made during their execution will still be connected to the root (unlike `setTimeout` or `afterEffects`). Being a function call it's good for abstracting reusable behaviours. In TodoMVC I use this trick to cause form focus on render of the edit input by:
```jsx
const setFocus = el => setTimeout(() => el.focus())

// in the view
<Show when={isEditing(todo.id)}>
    <input
      class="edit"
      value={todo.title}
      onFocusOut={save}
      onKeyUp={doneEditing}
      forwardRef={setFocus}
    />
</Show>
```

Thanks for pointing this out I will grab some of this and beef up the docs a bit.

**Comment by aguilera51284** [comment]
why you need `setTimeout` ?

**Comment by Seanmclem** [comment]
I am also wondering about the setTimeout. Is it so the ref'd element can render to the dom first?

**Comment by ryansolid** [comment]
Yes. Refs trigger synchronously as elements are created. But certain things aren't applicable until connected to the DOM. I wish I had a better custom binding example. I think there is one in Reddit. I will see if I can pull it out.

**Comment by Seanmclem** [comment]
So setTimeout is only needed if you need to access the ref as soon as possible? Is it that -all we need to do is wait for one js cycle so and the dom-ref will be accessible? Afterwards when you need to reference it -the ref will already be available?

**Comment by ryansolid** [comment]
I see 3 scenarios:
1. You want the ref immediately to do some reactive stuff or make composable behavior: use `forwardRef`
2. You want to do some action after being connected to DOM and painted. Use either method but use `setTimeout`. In rare cases where you want to get in before paint but after connected use `afterEffects`.
3. You don't care if the ref is there yet since it only matters for some event handler or reaction that will evaluate again anyway use `ref`.

Honestly I haven't come across the 3rd case yet which has me thinking about the validity of it. The ref is available immediately on the JSX evaluating. Technically if you assigned the JSX output to variable, then did something with the ref, and then returned the output it would work too but who wants to do that? The whole thing here is that Components only execute once so nothing will know its assigned. The biggest thing for me considering saying screw it and make them all callbacks. I do like the simple assignment form sometimes though as I need to do a `setTimeout` in many cases so it's less ceremonious.

**Comment by RishiSanghvi123** [comment]
What if I want to submit a form and pass a ref from the parent component?

So when the parent component invokes the child component, i want the form in the child component to submit itself. Can I do this using refs?

**Comment by kulak** [comment]
I'd like to point out that when using TypeScript it will compile, but generate error that variable is used before it is assigned ts(2454).

The workaround to this is use of `!`:

```ts
export function CompA() {
    let htmlDiv: HTMLDivElement
    onMount(()=> { /* use htmlDiv */ }
    // the following line is reported with ts(2454) and htmlDiv is the unassigned variable if `!` is removed.
    return <div ref={htmlDiv!}></div>
}
```

**Comment by agat** [comment]
> 
> ```ts
> let ref: HTMLDivElement | undefined = undefined
> ```
> 
> It might look ugly, but it is, what it is.

Or as variant

```tsx
let ref!: HTMLDivElement;

return <div ref={ref}></div>
```
