### ISSUE TITLE
CSS-in-JS unification

### ISSUE THREAD

**Issue by high1** [ryansolid/solid#137]
I know that the origin [issue](https://github.com/ryansolid/solid/issues/102) was closed yesterday, but I was wondering if releasing two implementations is the right resolution. I don't think that you need to implement all the possible options, but I think these two could be unified inside one solid-styled library which would have two sub exports, solid-styled/jsx and solid-styled/goober. It would be easy to add emotion to the mix, and expose it under solid-styled/emotion. With tree-shaking, build optimization would remove unneeded deps. The only downside I see is the initial library size, if emotion, styled-jsx and goober (ok, goober not really) would be direct dependencies. I know that solid-jsx implementation differs from the styled one, but I don't think that would be the issue. Maybe goober could be used for the default export, and if you want to use solid-jsx or emotion, install these manually - those would be peer dependencies.
```
import { css, cx, Interpolation } from 'emotion';
import { cloneProps } from 'solid-js';
import { spread } from 'solid-js/dom';

export default function styled<T extends Record<string, unknown>>(
  tag: string | ((props: Record<string, unknown>) => HTMLElement)
) {
  return (
    template: TemplateStringsArray,
    ...args: Array<Interpolation | ((props: Partial<Record<string, unknown>>) => Interpolation)>
  ) => {
    return (props: T & { className?: string }): HTMLElement => {
      const newProps = cloneProps(props);
      Object.defineProperty(newProps, 'className', {
        get() {
          let className = css(
            template,
            ...args.map((i) => (typeof i === 'function' ? i(props) : i))
          );
          className = 'className' in props ? cx(className, props.className) : className;

          return className;
        },
        configurable: true,
        enumerable: true,
      });

      let el;
      if (typeof tag === 'function') {
        el = tag(newProps);
      } else {
        el = document.createElement(tag);
        spread(el, newProps);
      }

      return el;
    };
  };
}
```

**Comment by ryansolid** [comment]
I debated something similar to this when I was still under the impression that I could share code somehow. The truth of the matter is each library has its own little niche, its own `css` functions, etc... Some have compilation options available.. different types of optimizations. They all are completely different and gain no benefit being shipped together, although grouping in a mono-repo makes sense as definitely to keep things easier to maintain for me.

My motivations come largely down to my time maintaining libraries. I wasn't sure I was going to release libraries myself. I ended up going the way I did mostly because I figured I should make a styled component library I could just point people to if necessary, and goober was fairly basic and non-obtrusive. But it's more of an implementation detail. Styled JSX is different. I felt that no-one was going to figure out how to make that work effectively and it broadened the type of library supported by Solid. It is also the most unobtrusive approach as it uses all their code and I just swap out one component. Both these do not behold me to do any additional work on them.

I considered Emotion as well, but ultimately felt CSS prop was a large part of their implementation and my approach to Styled Components was less optimal than what they do in their React implementation. The snippet above works fine as I showed in the demo but I didn't feel comfortable releasing it as Solid-Emotion, to me that would suggest doing more work to make more interoperability with their features. I would love to see someone consider taking it on but it wasn't for me at least not at this point. I am much more on the React view of things rather than the Vue thing. I've really tried avoiding to push libraries that could be made in the community (the only reason I haven't written a router) but I understand without the tools people won't use it, so may be destined.

But in that case my goal is to keep things minimal. This might be a philosophical thing to me but it is also definitely being pragmatic. I want to help the community as much as I can but I won't succeed at that by maintaining many more libraries.

**Comment by high1** [comment]
Completely agreed on this 
>  I am much more on the React view of things rather than the Vue thing
I have respect for what Vue is doing also, but it requires a lot more man power - one man is certainly not enough. I'll close this. Not sure if it is really worth it to pursue full emotion integration, as it is larger than solid itself, and it somehow defeats the goal of ultimate optimization you're pursuing.

**Comment by ryansolid** [comment]
I appreciate the understanding. Thanks.
