### ISSUE TITLE
wording: "onCleanup" vs "useCleanup", "sideEffect" vs "useEffect", etc

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#14]
Could it be more semantic to have functions like `useCleanup` and `useEffect` named `onCleanup` and `sideeffect` (and similar consideration for other functions)?

f.e.

```js
    const interval = setInterval(() => setState('counter', c => c + 1), 1000);
    onCleanup(() => clearInterval(interval))
    sideEffect(() => console.log(state.counter))
```

**Comment by ryansolid** [comment]
Mostly I just liked what React Hooks were doing and copied the convention. I realize these aren't exactly hooks in the same fashion since they get reconstructed when the outer context re-evaluates but out of the options I liked the familiarity. createState or createEffect is more accurate but I mostly like that by using Reacts syntax people immediately get it.

**Comment by ryansolid** [comment]
I'm starting think you are right. These aren't hooks so the semantics aren't right. I do still  think there is value in familiarity, but use suggests limitations of hooks that are not present here.

createState createEffect createMemo createSignal onCleanup createRoot can be the alternative. Any one else want to weigh in?
