### ISSUE TITLE
Solid-styled-components passing data-attributes fails

### ISSUE THREAD

**Issue by praneybehl** [ryansolid/solid#149]
Sandbox: https://codesandbox.io/s/solid-styled-components-bug-pofbj?file=/index.js

There seems to be an issue when trying to pass data-attributes through solid-styled-components. 
It should be able to pass valid HTML attributes eg. data-*, aria-* etc... down to the html.

On the sandbox it throws an error whereas, running the code locally, no errors that thrown just the data attributes are stripped

**Comment by ryansolid** [comment]
@praneybehl 
This looks awfully similar to https://github.com/ryansolid/solid/issues/146.
Can you confirm that you have the latest version of babel-plugin-jsx-dom-expressions in your deps.. Should be 0.17.5.

**Comment by ryansolid** [comment]
Ok reviewed this further. I did fix the Component passing issue (although Code Sandbox likes to cache stuff forever) but not the runtime spread issue. It is not using the right heuristic to determine it's an attribute and setting it as property which does nothing. I am working in this area right now, so I should have it fixed in the next minor version of Solid.

**Comment by ryansolid** [comment]
I'm happy to report this is fixed in v0.18.0.
