### ISSUE TITLE
Memo not updating within mapArray

### ISSUE THREAD

**Issue by rturnq** [ryansolid/solid#151]
There seems to be an issue with memos when used in a component rendered by `For` and more specifically `mapArray`. Here is a reproducible example: https://codesandbox.io/s/solidmaparray-memos-v8un0 (you may have to click the refresh icon on the browser output window if nothing appears).

The symptom I see is that the first memo created within each component rendered for each item in the array doesn't update. Subsequent memos appear to work correctly. I initially noticed this when using a `Show` - its condition is memoized within the `Show` component and it never seemed to update.

In my example, in each `Row` I create three identical memos which track the `isNew` property of the array item. This property is initially true when the item is added and is set to false once you type anything into the text input. The value of each memo is rendered which make it clear that the first never changes. Additionally I used a plain map to render the same rows and the memos work as expected - though using a For is much more desirable for reducing re-renders when the array changes.

**Comment by ryansolid** [comment]
Yeah something weird is going on. If I remove the createMemo's(and just execute the functions) it still happens which makes me think that something else is going on. I will need to dig in to this a bit. Thanks for reporting.

**Comment by ryansolid** [comment]
I figured it out. Bug in my new reactive system when tracing upstream computations with nested roots. Basically since updating the item causes the list to update it gets in a state where it goes to process the row grabs the first computation and thinks that something upstream is going to update anyway and evaluates that instead. Since it doesn't actually get disposed the rest of the row computations then fire off after. I just need to have it recognize that it is in an independent root so it shouldn't consider any parents above that as things that would cause it to be disposed.

Thank you for finding this. It's definitely on the edge case side of things but I am not sure when I would have found it otherwise. I will likely put this in the upcoming release rather than push something right away.

**Comment by ryansolid** [comment]
I'm happy to report this is fixed in v0.18.0.
