### ISSUE TITLE
About the "each" directive time complexity when updating

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [ryansolid/solid#16]
For example this code in rendering.md:
```js
<ul>
  <$ each={ state.users }>{
    user => <li>
      <div>{( user.firstName )}</div>
      <$ when={ user.stars > 100 }>
        <div>Verified</div>
      </$>
    </li>
  }</$>
</ul>
```
The only way to change state.users for solid.js is making a new array, so time complexity is O(n):
```js
setState({
   users: [...state.users, { firstName: "Tom", stars: 10 } ] // clone state.users and add a new element
})
```
And because of this, solid.js has to scan old array and new array to know what dom element to remove and what dom element to add, so the time complexity is also O(n).
So can I do anything to lower this, like the "vanilajs" implementation on https://github.com/krausest/js-framework-benchmark which has O(1) complexity for updating an element in array?

**Comment by ryansolid** [comment]
It is possible to do a deep set here but ultimately it isn't going to improve the performance of reconciliation in a noticeable way:

```js
setState('users', {[state.users.length]: { firstName: "Tom", stars: 10 });
```
In this case we don't clone the array just update the index. So now the data update phase is O(1). If you look at the implementation of Swap rows for Solid in the js-framework-benchmark you see this in action.

It comes done to the computations used in the change detection library are set up to be triggered off multiple sources so you never know exactly what has changed or what dep triggered it.  I was experimenting at one point with my own change detection library to pass that along the specific change but the overhead of my method wasn't worth the cost in the vast majority of cases. This is definitely an area of research.

The Each binding already has a slight win since typically with JSX based libraries you have this issue where it executes inside out. So generally reconciliation would work like:

1. Handler - Update data
2. MapFn in JSX - transform data to nodes (look up memoized values)
3. Insert in JSX - reconcile node array changes against actual DOM

In the naive case it's O(n), O(n^2) and O(n^2). Most performant libraries do smarter algorithms to prevent needing to check every old value against every new value each time to get to roughly O(n) for each 2 and 3. With Solid I introduced Each to combine phase 2 and 3 together so I could do them in a single pass. In practice it had an almost unnoticeable performance impact (although it had some other benefits). 

That's the thing here.  Compare the Swap Row performance between all libraries. I acknowledge it's the shortcutting optimization that we do for any single row operations that makes this so performant. But once the changes are significantly complex you are really weighing doing diff vs recording sequences of mutations (order matters if inserting/removing in the middle). What I find that happens is you endup reconciling the mutations anyway which doesn't actually simplify anything. Not that I don't believe this could potentially be more optimized than what I have today it's just considerably more involved.

Once you get beyond a certain number of rows a different solution is needed anyway to gain performance (windowing etc). The place where a library like Solid really takes the hit is the overhead around initial construction and teardown. I actually de-optimized some of the setters in the benchmark for clarity of implementation code, but appendRows could be related (although I had associated with simply the creation overhead). I will do some more experiments. Thanks for the thoughts.

**Comment by ryansolid** [comment]
Where things have headed. I've actually separated the reactive list processing from the DOM reconciliation to allow for easier and more flexible use of the library. While there might be a way to improve the array changes on the reactive system side I do not believe it will yield much compared to the DOM reconciliation side which is unlikely to benefit. I think since my previous answer no longer holds up I'm going to close this issue to prevent future confusion.
