### ISSUE TITLE
Hot reload for solid with snowpack

### ISSUE THREAD

**Issue by ravupad** [ryansolid/solid#164]
Has someone succeeded with hot reload for solid with snowpack?

**Comment by ryansolid** [comment]
Not sure... Has anyone used Solid yet with Snowpack? I haven't seen any starters for it yet.

Most questions/issues seem to be about Webpack. I use Rollup for most of my stuff. A lot of people have been leaning on Parcel 2 for its simplicity (and it's how to do TS in CodeSandbox).

I haven't had a change to dig into Snowpack yet but seems interesting. Have any of you?

**Comment by ravupad** [comment]
I have create a solid snowpack starter template [1].
There is a section for enabling HMR in snowpack which  seems simple [2].

[1] https://github.com/ravupad/solid-snowpack-starter
[2] http://snowpack.dev/#hot-module-replacement

**Comment by ryansolid** [comment]
Is there any equivalent of a loader like in Webpack? The approach I've used to date is add individual wrappers around modules so I can hot replace them in the reactive graph: https://github.com/ryansolid/solid-hot-loader/blob/master/index.js#L3

I'm not sure how to do it another way. Since a Component in Solid itself is just a function call and doesn't own its state. The nested computations do.

**Comment by high1** [comment]
Why don't you try and add import.meta.hot.accept()? My guess is that it will not work, it will just render another instance of the mounted DOM node. Is there a way to replace or update the current DOM node?

**Comment by ravupad** [comment]
Yes @high1. I tried that. Here is the [code](https://github.com/ravupad/solid-snowpack-starter/blob/hmr/src/index.jsx).

```js
if (import.meta.hot) {
  import.meta.hot.accept(({module}) => {
    console.log(module);
  });
  import.meta.hot.dispose(() => {
    document.getElementById('root').innerHTML = '';
  });
}
```

But this results in everything being reset. And another problem is that maybe because the components are not getting disposed properly, cleanup code is also not getting called.

**Comment by high1** [comment]
You are invalidating innerHTML of the mounting DOM node, that is far from hot reloading.

**Comment by ravupad** [comment]
Yes. There was a minor issue in code. I fixed it. The update code is [here](https://github.com/ravupad/solid-snowpack-starter/blob/21c31ca7d9fbc5c8ac5ad907d23de40beca05773/src/index.jsx).

Logs from console on (adding just a blank in file and saving it) are
```
[ESM-HMR] message {type: "update", url: "/_dist_/index.js"}
hmr.js:6 [ESM-HMR] message: update {type: "update", url: "/_dist_/index.js"}
hmr.js:6 [ESM-HMR] /_dist_/index.js ["/_dist_/index.js"]
index.js:84 hmr dispose
index.js?mtime=1591092719873:74 rendering app
index.js:39 cleanup of A
index.js:81 hmr update Module {Symbol(Symbol.toStringTag): "Module"}
```

The behaviour in browser is that another `A` component gets added in `root` node, and all the `A` components are increasing in size due to `A`'s interval.

**Comment by high1** [comment]
Hm, I'm not convinced at all. You're just logging the output in the callbacks - the node will be duplicated, if I'm correct. If you try the React template, they have true hot reload which keeps the state.

**Comment by high1** [comment]
You're just logging the output in the hmr branch - this should only duplicate the nodes.

**Comment by ravupad** [comment]
@ryansolid, as @high1 mentioned, is there a way to destroy a render?

**Comment by ryansolid** [comment]
There is a way to release the whole tree by calling the returned dispose method and `textContent = ""` the mount element, but that approach will never give you the granularity you seek. What I was trying to say in my earlier comment is the problem with approaching HMR this way is even if you succeed is switching the module there is no reason for anything already mounted to re-run. You'd just be reconstructing it and all it's children. Which is fine start, but the component doesn't own it's own insertion.

The best way I've found to do that is to take the same technique I highlighted in #73 and #163 to basically make the component change trigger the reactive graph from that point down. I did this with webpack by using a loader to wrap the default export of component files. There may be a way to do this with Babel. But essentially my thinking is if at each component insertion we track the component we are using in a computation, when we hot load the new one in we are just triggering that scope and inserting. The cleanup takes care of itself because it's in the reactive graph.

I'm open to other thoughts and suggestions. It would be interesting to be able to do it from the root. Maybe there is an approach that doesn't require transformation like a manual opt in HOC that is a no-op if you don't turn some config on.

**Comment by high1** [comment]
The problem I see here which comes with the reactive approach is that DOM is not a part of the reactive graph - so you would need to re-render the DOM from one point downwards - virtual DOM libraries do that anyway, so they can just add another re-render call here. Svelte implementation makes sense from the reactive point of view for me - just reload.

**Comment by ryansolid** [comment]
So are we suggesting something as simple as:

```jsx
import { render } from "solid-js/dom";
import App from "./App";

let mountEl = document.getElementById("main"),
  dispose = render(App, mountEl);

// Hot Module Replacement (HMR) - Remove this snippet to remove HMR.
// Learn more: https://www.snowpack.dev/#hot-module-replacement
if (import.meta.hot) {
  import.meta.hot.accept();
  import.meta.hot.dispose(() => {
    dispose();
    mountEl.textContent = "";
  });
}
```

**Comment by ryansolid** [comment]
This issue is inactive. Good discussion is happening over on the discord on this and similar topics. Closing.

**Comment by clinuxrulz** [comment]
Here is a trick, but I'm using rollup:

```
import { render } from 'solid-js/web';
import App from './components/App';
import './main.css';
import wasm from "../../Cargo.toml";

const root = document.querySelector('#app');
let saveAppState;
let restoreAppState;
if (root) {
  async function load() {
    let rust = await wasm();
    document.body.appendChild(root);
    render(() => <App wasm={rust} onOnSaveAppState={x => { saveAppState = x; }} onOnRestoreAppState={x => { restoreAppState = x; }}/>, root);
    restoreAppState();
  }
  load();
}

export const moduleHotAccept = (mod) => 
    mod?.hot?.accept(() => {
      saveAppState();
      window.location.reload();
    });

moduleHotAccept(module);
```

Then inside App.jsx we have:
```
    if (props.onOnSaveAppState) {
        (props.onOnSaveAppState)(() => {
            Cookies.set("AppState", JSON.stringify(appState));
        });
    }
    if (props.onOnRestoreAppState) {
        (props.onOnRestoreAppState)(() => {
            let appState = Cookies.get("AppState");
            if (appState == undefined) {
                return;
            }
            setAppState(JSON.parse(Cookies.get("AppState")));
        });
    }
```

It just saves on having to navigate to the app tab each time to see how the view your working on changes with code changes live. Just slower because it is still reloading the entire app.

**Comment by clinuxrulz** [comment]
Nevermind. I switch to vitejs bundler and works amazing. I had no idea proper HMR was done yet.

**Comment by ryansolid** [comment]
It should be workable into Snowpack but I haven't tried it yet.

**Comment by davedbase** [comment]
I believe amoutonbrady already has this working with Snowpack: https://github.com/amoutonbrady/snowpack-solid
