### ISSUE TITLE
[docs] browser support

### ISSUE THREAD

**Issue by benmccann** [ryansolid/solid#177]
Something I didn't see mentioned in the docs that would be useful to add - what browsers does Solid run on? What polyfills or transpiling is necessary to support older browsers?

**Comment by ryansolid** [comment]
Hmm... I guess this question is more or less the IE test these days.

Short Answer: The last 2 versions of modern evergreen browsers and Node LTS. 

Longer Answer:

Non-Chromium Edge and Safari before 12.1 will need to polyfill `globalThis`.

As for IE I mean there are a lot of missing things, but I never considered IE when I built this library primarily on Proxies which are notoriously difficult to polyfill. It is possible to use Solid without the proxies but I imagine that would require polyfilling Promises, Symbols, and some Array methods. Honestly not sure what else since I've never given it any consideration. I think I'm ok just saying no support of IE at this point, and if someone finds a way that's awesome.

I have added the short answer to the readme and I have signed up for Open Sauce so I can add browser tests.

**Comment by aminya** [comment]
There are a couple of things that can be optimized for the browser by setting the known global variables.

https://github.com/ryansolid/solid/search?q=globalThis

For example, in the browser, this `globalThis._$HYDRATION` is always false. Terser for example allows minifying these.
(.terserrc.js)
```
export default {
  compress: {
    global_defs: {
      "globalThis._$HYDRATION": false,
    },
	// ...
  }
  // ...
}
```
There are other tools for other build tools (e.g. rollup-plugin-replace).

**Comment by ryansolid** [comment]
Yeah that's a good point. I've been working really hard on the new version to make the code splitting handle this for us automatically. Basically assign to variables that are only assigned in the `hydrate` method so that rollup is smart enough to realize that the variable is never assigned and the code can just be eliminated but I imagine it might still leak in. Especially as not all bundlers work as effectively as Rollup.

**Comment by ryansolid** [comment]
I should add with Solid 0.24.0 Solid pretty much drops support for IE. Proxies are necessary to handle more complicated prop scenarios like Spreads. I wasn't doing them very well before but now that I am IE is good as done.

**Comment by aminya** [comment]
> Yeah that's a good point. I've been working really hard on the new version to make the code splitting handle this for us automatically. Basically assign to variables that are only assigned in the hydrate method so that rollup is smart enough to realize that the variable is never assigned and the code can just be eliminated but I imagine it might still leak in. Especially as not all bundlers work as effectively as Rollup.

It is also possible to ship prebuilt solid bundles for different purposes.

> I should add with Solid 0.24.0 Solid pretty much drops support for IE.

Thank you so much for dropping IE. 🎉 

 If the developers stop supporting IE like how Microsoft did, normal people will also be forced to use newer browsers since they will see that their browsers keep altering them to use a new browser, and the modern websites stop working for them.

**Comment by ryansolid** [comment]
I mean technically I never supported it. But it was possible with the right polyfills and avoiding certain features. Now Solid just can't work in IE even if you tried.

**Comment by ryansolid** [comment]
This one is long done. Closing.
