### ISSUE TITLE
createResource loading never switching to false

### ISSUE THREAD

**Issue by Akkuma** [ryansolid/solid#188]
I'm running the following code:
```js
import { createResource } from 'solid-js';
import { render, Suspense, Switch, Match } from 'solid-js/dom';

function getUserMedia(deviceId) {
  return navigator.mediaDevices.getUserMedia({ audio: deviceId ? { deviceId } : true });
}

function enumerateDevices() {
  return navigator.mediaDevices.enumerateDevices();
}

render(
  _ => {
    const [ hasAudioPermission, load ] = createResource();
    load(getUserMedia())

    return (
      <Suspense fallback={<div>You must answer to do this shiznit</div>}>
        <Switch>
          <Match when={hasAudioPermission.loading}>
            <p>Select the shiznit</p>
          </Match>
          <Match when={hasAudioPermission()}>{
            _ => {
              const [ devices, load ] = createResource();
              load(enumerateDevices())

              return (
                <Switch>
                  <Match when={devices.loading}>
                    <p>Grabbing audio devices</p>
                  </Match>
                  <Match when={devices()}>
                    <p>{JSON.stringify(devices())}</p>
                  </Match>
                </Switch>
              );
            }
          }
          </Match>
        </Switch>
      </Suspense>
    )
  },
  document.body
);
```

I'm seeing `<p>Select the shiznit</p>` appear alongside the second match. I even tried replacing the second match from the first Switch with a simple `<p>Other content</p>` instead of my nested Switch, but still saw the same result.

I'm running 0.18.12

**Comment by ryansolid** [comment]
Yeah it looks like there is an issue with nested control flows with cascading async loading under Suspense. Thanks for reporting. I will look into this.

**Comment by ryansolid** [comment]
Ok I actually found out the actual reason wasn't what I earlier thought. I probably need to emphasize this and I have some bad examples, but the problem is that when we insert directly into the body and there are other elements it gets messed when there is complicated reconciliation. You should always insert into a mount element that the library can own all the children for. This is common practice in React etc.. I just hadn't worked out that it needed to be the same way here. I will update docs and examples accordingly.

So to be clear the element in the render function should have no children before you call render.

**Comment by mikefrancis** [comment]
Just had the same issue, possibly a bit of a heavy handed fix but solved it by wrapping my component return in a fragment.
