### ISSUE TITLE
Solid + webpack + TypeScript without babel?

### ISSUE THREAD

**Issue by benrbray** [ryansolid/solid#195]
I'm interested in adding Solid to an Electron application already in development.  I'm using [`electron-webpack`](https://webpack.electron.build/), which defines sensible defaults for project structure and webpack config.  Since there is no reason for an Electron app to use polyfills, the project currently does not use `babel` (of `babel-loader` from webpack).

I'd like to try out Solid for the UI, but the recommended way to set up Solid seems to rely on `babel-loader` with the `babel-preset-solid` preset.  After much difficulty, I was able to add Solid to my project with the following steps:

1. [Modify the default config](https://webpack.electron.build/modifying-webpack-configurations#using-a-config-function) of `electron-webpack` to use `babel-loader` with `babel-preset-solid`

```js
{
  "test": /.jsx$/,
  "loader": "babel-loader",
  "options": {
      "babelrc": false,
      "presets": [
        "@babel/preset-env",
        "solid",
        "@babel/preset-typescript"
    ],
    "plugins": [
        "@babel/proposal-class-properties"
    ],
      "cacheDirectory": true,
      "cacheCompression": false,
      "compact": false
  }
}
```

2. Resolve all the [regeneratorRuntime is not defined errors](https://stackoverflow.com/questions/53558916/babel-7-referenceerror-regeneratorruntime-is-not-defined) by installing `core-js` and `regenerator-runtime` and importing them in a few places.

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

I'm not too familiar with babel, but it seems like quite a big dependency to add and I'd like to avoid it if possible.  Already, my compile time is slower and babel has added hundreds of dependencies! 

1. Is babel necessary to run solid?  For example, it'd be great if there were a "solid-loader" for webpack instead.
2. Alternatively, I wonder if it's possible to use the `tsxFactory` option in `tsconfig.json` to avoid the Babel step and have `ts-loader` run solid instead
3. If there's no alternative to using `babel-preset-solid` for solid's compilation phase, would you be able to give any suggestions for disabling any features of babel that are not necessary to run solid?

Thanks!

**Comment by ryansolid** [comment]
Babel is currently necessary as it does the custom transformation. A solid-loader for Webpack would still require loading a parser and transformation library. Libraries like Svelte and Vue have their own, I used Babel since it already has all the pieces I needed. Unfortunately like Svelte and Vue, Solid's transformation with JSX is custom.. there is a way to make it work with standard transformation, but you don't want to do that. It removes the biggest performance benefits and changes the syntax of the JSX. 

Babel in itself does very little. It just parses, applies transformations, and creates source maps. All compile-time dependencies. The issues you are having are all around `preset-env` which is designed to transpile from whatever JavaScript you have to a specific target. In so things that require polyfills are pulled in when the target env doesn't support them. I don't know what Electrons platform limits are but preset-env is why corejs and regeneratorRuntime are getting pulled in. In current Node or an Evergreen browser like chrome you wouldn't even need `preset-env` and basically have no runtime overhead. But Electron might not support certain features used by Solid.

You can set the target with preset env (so it doesn't default to basically IE11 compatible ES5) and you won't need to pull that other garbage in. I believe you can set your electron version. https://babeljs.io/docs/en/babel-preset-env#targets. I am just not that familiar with Electron so I don't know how modern the platform it is running on is.

**Comment by benrbray** [comment]
Thanks for the tip about preset-env!  I didn't know it was possible to target `electron` directly, and that seemed to do the trick.  New webpack config rule:

```js
{
	"test": {},
	"loader": "babel-loader",
	"options": {
	"babelrc": false,
	"presets": [
		[
		"@babel/preset-env",
		{ "targets": { "electron": "9.0.2" } }
		],
		"solid",
		"@babel/preset-typescript"
	],
	"cacheDirectory": true,
	"cacheCompression": false,
	"compact": false
	}
}
```

Here are some links I found helpful for anyone who comes across this issue in the future:

* https://babeljs.io/docs/en/babel-preset-env#targets
* https://github.com/babel/babel-preset-env/issues/326
* https://github.com/babel/babel/issues/9971
