### ISSUE TITLE
Making the component body reactive

### ISSUE THREAD

**Issue by whatisaphone** [ryansolid/solid#200]
I'm only just exploring the framework, so bear with me here.

So in a component, outside of JSX expressions, you can't directly access reactive state, or it will no longer be reactive.

```js
// Wrong!
function UserName(props) {
  const user = props.user;
  const fullName = `${user.firstName} ${user.lastName}`;
  return <div>{fullName}</div>;
}

// Right!
  const user = () => props.user;
  const fullName = () => `${user().firstName} ${user().lastName}`;
```

But in a component with a lot of intermediate calculations, that's a lot of noisy `const foo = () =>` and `foo()` all over the place. I really find myself wishing that the entire component body was reactive, instead of just the JSX expression. You can already "fake it" today like this:
﻿
```﻿js
function UserName(props) {
  return () => {
    // Look ma, no thunks!
    const user = props.user;
    const fullName = `${user.firstName} ${user.lastName}`;
    return <div>{fullName}</div>;
  };
}
```

We used to use mobx-react at $dayjob and their `﻿@observer﻿` similarly encompasses the entire function body.
﻿
What if the babel plugin, instead of wrapping each JSX expression, wrapped the entire component body? This would make the cleaner-looking `// Wrong!` example above behave as expected. Having briefly thought about it, I don't think it would hurt performance, since you wouldn't be doing more wrapping or more work, you're just moving more statements inside the wrapper that already exists today. Perhaps it could even slightly improve performance since you'd have less intermediate thunks in typical userland code (so less allocation and indirection). And depending on how it interacts with esnext downleveling, maybe it could even let destructured props remain reactive.

Would there be any downsides to this that I haven't considered?

**Comment by ryansolid** [comment]
Yeah unfortunately this is something that I do not believe is avoidable. Forgive me if the answer seems like a bit of dump but this is something that has been very much on my mind since I first started this 5 years ago. I wanted everything to be easy. There is a reason why you haven't seen a React compiler approach with JSX. People say it's impossible. I don't think that's true but there is definitely reasons we haven't seen it and I solved the problem in a very different way.

There is a huge performance consideration here when you don't use a Virtual DOM for anything non-trivial. In your example what you wrote roughly compiles like this:

```jsx
function UserName(props) {
  return () => {
    // Look ma, no thunks!
    const user = props.user;
    const fullName = `${user.firstName} ${user.lastName}`;
    return <div>{fullName}</div>;
  };
}
// becomes
function UserName(props) {
  return () => {
    // Look ma, no thunks!
    const user = props.user;
    const fullName = `${user.firstName} ${user.lastName}`;
    
    // create a new div element every time I execute
    const div = document.createElement("div")
    div.textContent = fullName;
    return div;
  };
}
```

If you assume that function that you return is a `createEffect` that replaces the previous value with the current you are pretty much there. So in this scenario you are creating a new div every time and replacing it rather than just updating the text. If your returned template has child components or anything else it does you'd pretty much be re-recreating the whole tree downwards from that point.v So the only reason wrapping everything like the example works with control flow is it either does its own memorization in the component or it guards against unnecessary changes. But wrapping full components would recreate everything on any change.

In fact is more or less how React works. Even with `React.memo` (or MobX) skipping parts of the tree it still all runs top-down. But since it renders a cheap virtual DOM and diffs it this cost is mitigated. Without a Virtual DOM you don't have this luxury. Sure you could do similar memorization but it still this top-down diffing process. You need to know what was at the position on the previous render.

Now there are ways around this if you make the Components a thing. Ie from a compilation standpoint for that scope you split initialization and update paths. This is what Svelte does. But requires you calling components out from a compiler standpoint. Most commonly this is done with single-file components. Notice how they always split the code from the template in those. It has a second purpose of isolating the view part of the codes to handle it under a different context. Something as fluid as JSX could be problematic and is largely why Svelte says it won't support JSX etc. Vue does the same split too. Now you could handle this with something like Vue's config objects and `setup` functions but that has it's own fun (see things like `toRefs`).

I hope that makes sense. Shoot over any more questions you have. People often have this thought at first which means I might not be doing the best to explain it. There also are big performance gain potential in removing heavier components from the equation. Part of the reason Solid regularly outperforms Svelte in benchmarks. But I understand performance isn't everything. But it was the unique direction I wanted to explore but like anything it isn't without tradeoffs.

**Comment by whatisaphone** [comment]
Thanks for the brain dump. You're right about my code—in the devtools I can see the div being recreated each change. So I guess those thunks (including the one the compiler inserts around JSX) are the "units of reactivity" and should actually be kept as granular as possible to minimize DOM operations.

Clearly you've put a lot more thought into this than I have!

**Comment by ryansolid** [comment]
Thanks for bringing this up. It's a pretty common thought. Destructuring not working is really annoying from a convenience standpoint. Nothing is without tradeoffs. At least this is mostly syntaxual.
