### ISSUE TITLE
More concise way of making controlled components

### ISSUE THREAD

**Issue by Koxiaet** [ryansolid/solid#207]
To make a controlled component, currently you have to write out:

```jsx
<input value={some_state()} onInput={e => set_some_state(e.target.value)} />
```

This is quite long and boilerplatey for such a common pattern. I propose a shorthand syntax that looks like this:

```jsx
<input model={[some_state, set_some_state]} />
```

It's inspired by Vue's `v-model`.

**Comment by bikeshedder** [comment]
You can create your own `<Input>` (uppercase "i") component which does exactly that.

```jsx
function Input(props) {
    return <input value={props.model[0]()} onInput={e => props.model[1](e.target.value)} />
}
```

I do agree that `onInput` is rather unwieldy. tbh. if you're going to define your own `Input` component anyways I don't see how a `model` prop combining setter and getter in an array is any better than having the parameters separate:

```jsx
function Input(props) {
    return <input value={props.value} onChange={e => props.onTextInput(e.target.value)} />
}
```

```jsx
<Input value={some_state()} onTextInput={set_some_state}>
```

I don't think solid should be monkey patching browser builtin components and add features like `model`. This is probably best done in a component library.

**Comment by Koxiaet** [comment]
There is already precedent for adding new attributes in this library, for example `ref`. I don't think such a small feature as this is even worth making a wrapper for - if it's in the base library people will use it but otherwise there's just a useless layer of indirection and doing it manually will be better.

The advantage of having it in an array is to support directly putting the output of `createState`/`createSignal` inside if people want to. It's also less characters to type, which is the whole point of this extension.

**Comment by ryansolid** [comment]
I've been exploring a syntax for custom directives and I think this is a good candidate for it. My experience with 2 way binding is it assumes too much. What events to listen to, when to propagate change. I do think there is probably an 80% case here but I also think it's the type of thing to turn over to userland. I think with an easy detectable syntax and a standardized directive writing format you could write something that was reusable and work exactly as you desire. What I am less clear about if it makes sense for Components to have them. Components can really only forward refs and this mechanism is more or less a syntax sugar over ref. Like today you could do this through function composition with refs. But the syntax is way bulkier.

```jsx
<input ref={model(some_state, set_some_state)}/>
```

As long as `model` returns a function that passes the input element you wire up what ever you want. But I imagine you rather do this:
```jsx
<input $:model={[some_state, set_some_state]}/>
```
I'm definitely considering if it's consistent enough and if there are other implications.

**Comment by Koxiaet** [comment]
Can't this already be implemented today?

```tsx
const ModelComponent = (props: {
    model: [() => string, (value: string) => void],
}) => ...
```

**Comment by ryansolid** [comment]
The fact it's `model` holds no special meaning. It does nothing unless the Component does something with that prop with its internals or children. Whereas this needs/leverages special compile time consideration with intrinsic DOM elements. Using props to forward through is fine but if we adopted a special syntax like say one that uses JSX Namespaces it wouldn't make sense for those to be appllied to components. 

Similarly with @bikeshedder example, which I'm generally behind, sort of locks you into specific children structure. Sure you could pass a tag as a prop and use `Dynamic` to create elements. But the potential for these sort of reusable things seems good for using on a variety intrinsic DOM elements. I was just commenting the special syntax isn't really transferable through components  It probably isn't a real problem but it is one of those things.

**Comment by Koxiaet** [comment]
To clarify, are you suggesting that you add the ability to make custom user-defined attributes that apply only to intrinsic DOM elements? So I can define my `model` in user code and have it apply to all `<input>`s automatically.

**Comment by ryansolid** [comment]
I mean that you could apply it to whatever intrinsic element you wanted to (or you decided to support). Basically a nicer syntax around ref. So say you defined:

```js
function model(el, options) {
  const [get, set] = options;
  createEffect(() => el.value = get());
  el.oninput = (e) => set(e.target.value);
}
```
You could import it in any file and the compiler would know to call it the right way because it's prefixed with `$:`
```jsx
<input $:model={[some_state, set_some_state]}/>
```
Given `ref` and Component composition not sure it's necessary but it's maybe another option. I've been eagerly waiting for TypeScript to unbreak this.

**Comment by ryansolid** [comment]
Another option is not do this and just use `ref` with your own function. It is much more explicit. And technically multiple `ref`'s work if it wasn't for TypeScript. I have a temporary bug right now preventing the syntax (introduced in this version) that I will fix in the next release but if I allowed for numbered refs to fool TypeScript maybe that is reasonable. so you could use `ref`, `ref2`, `ref3` or something like that. Pretend autofocus is another custom directive that gives the element focus when it first is rendered.

```jsx
<input ref={model(some_state, set_some_state)} ref2={autofocus}/>
```

Instead of:
```jsx
<input $:model={[some_state, set_some_state]} $:autofocus />
```

I should create an RFC.

**Comment by Koxiaet** [comment]
I think `ref` is somewhat of a confusing name for this. `with` would look a lot more intuitive:

```jsx
<input with={model(some_state, set_some_state)} />
```

Maybe `ref`'s function syntax could be replaced with `with`, or at least `with` could be added. Doing this would also reduce confusion between the two syntaxes:

```jsx
let autofocus = el => el.focus();
let my_input;
// Currently there is no visual difference between the two despite the fact
// that they do vastly different things.
return <input ref={my_input} ref2={autofocus} />
```

Also, `ref` could support an array - that would solve the multiple-refs issue in a clean-ish way, for example:

```jsx
<input ref={[model(some_state, set_some_state), autofocus]} />
```

And just for reference here's the `model` function written using refs:

```js
function model(state, set_state) {
	return el => {
		createEffect(() => el.value = state());
		el.addEventListener("change", () => set_state(el.value));
	};
}
```

**Comment by ryansolid** [comment]
If you mean way different by assignable vs call a function we used have a different name(`forwardRef`) but it ended up being a constant source of confusion. But I see this is non-explicit which could be confusing in its own right. It's possible assignment refs are just not necessary as well given the granularity often needs them to be wrapped in something. The best use case of assignment refs I feel is to pass a reference from a parent to a child.

I hadn't considered arrays since assignment refs wouldn't work easily at runtime. Although I suppose if it was a compiler syntax like I do with event binding that would be fine. Ie.. you can't pass a var and expect it to resolve that it's an array at runtime. The compiler looks for the array and transforms it appropriately ahead of time. Otherwise, I'd need to say that array refs can only be function refs. The challenge here is of course spreads and propagation from parent components. Although I guess I have that issue with all these solutions. In general, you wouldn't be passing the custom directive as a prop, just arguments to augment it so I think that is fine, although I'm sure someone will find some use case I'm not thinking of.

I think I like the array approach, might even play nicer with TypeScript. I will definitely add it to the list.

**Comment by mikeplus64** [comment]
Having `ref` support an array of ref functions would be quite nice... but I also think that solid should aim to have as minimal as possible a compiler because this will make it possible/easier to support platforms other than Babel in future. I strongly think Solid should do as little magic as it possibly can with its JSX compiler.

As is it's pretty easy to make your own combinator like

```typescript
const refs: <Ref>(...fs: ((ref: Ref) => void)[]) => (ref: Ref) => void = (...fs) => ref => fs.map(f => f(ref));
<input ref={refs(autofocus, controlled(some_state, set_some_state))} />
```

I don't think adding a `with` alias is worth it, for better or worse the naming of `ref` ship probably sailed with React a long time ago.

**Comment by ryansolid** [comment]
I've added the use directive which will be the solution here. https://github.com/ryansolid/solid/blob/master/documentation/rendering.md#custom-directives. I feel this covers this use case adequately and the extent I intend to do at this time.
