### ISSUE TITLE
Show can unexpectedly cause many DOM updates when used with objects

### ISSUE THREAD

**Issue by Koxiaet** [ryansolid/solid#218]
[Here is a codesandbox demonstrating the problem](https://codesandbox.io/s/solid-counter-forked-q8yy8). When the Increment button is clicked, the entire `<p>` showing the counter is recreated and added to the DOM instead of just the parts that needed to be changed.

Of course in this case the solution would be to replace `setState({ a: { b: state.a.b + 1 } })` with `setState("a", { b: state.a.b + 1 })`, but when the state is immutable this is not possible.

**Comment by ryansolid** [comment]
If you want to diff the data you there is a way to do that see `reconcile` https://github.com/ryansolid/solid/blob/master/documentation/state.md#reconcilevalue-options

Otherwise this is pretty much impossible to do efficiently. By default Solid does not diff. You have to opt into it as it has significant overhead and if you use certain patterns it is mostly unnecessary.

The mentality here is immutability is important in terms of contract and control but there is always a place where you know what you are changing. Immutable data loses that locality as once you change something nested you call in to question everything above it. `reconcile` is the escape hatch to do that automatically but you are always better to just do the finer update. I've borrowed from APIs similar to ImmutableJS to provide that experience. In the example you'd probably want to do:

```js
setState("a", "b", s => s + 1)
```

I realize I'm just extending your point that you don't have a way to preserve that knowledge as you are just getting a big object in. It's unfortunate but I understand that often the application architecture requires it. So hopefully `reconcile` works for you. I'm interested in ways we can make it more useful to fit more cases. But understand it is a bridge a fundamental different approach to managing state changes.

**Comment by Koxiaet** [comment]
In my actual code my state is a memo that depends on an action signal, so I have to use immutability and whole-object updates.

I thought that Solid did diff, because for everything else in the code no extra DOM updates are needed, just in this case. But maybe that's something else?

**Comment by ryansolid** [comment]
It diffs simple values sometimes at the dom level to prevent unnecessary updates but it's shallow. Generally the key to the performance here is that there is no diffing. We setup fine grained subscriptions so whenever data changes it knows exactly what to change. In this scenario you don't need any complex diffing and I do all the work ahead at compilation time or on initial render. I do some reconciling around lists but simple updates sort of dumbly propagate. Very simplistic. If coming from immutable data and need to force it into more granular updates state is probably your best bet rather than a signal. I typically use that `reconcile` to interface with like Redux or Apollo so that the rest of the Solid runtime can be the most efficient.

**Comment by rturnq** [comment]
I think there is a little more to the story here. I ran into a similar situation in the router I wrote and it comes down to the render function form.

We have gotten used to the idea in Solid that our component functions only run one time on creation and the reactive system takes it from there; however, in the case of a render function like this, any time value returned from `when` changes, your render function will execute again resulting in a new paragraph element which replaces the previous one. So these things work more like a React component in that they run every time the function arguments (props?) change. React of course gets around it with their vdom and reconciliation steps. So while I really like the render function pattern, in Solid, it does require you to think in two different ways about how rendering works.

In this case, in addition to using reconcile to prevent `state.a` from changing in the first place, you could also wrap your it in a getter and return that from the `when` so the Show component only sees changes between `false` and `getA` and let the reactive system handle updating the rest.

```
const getA = () => state.a;

return (
  <>
    <Show when={state.a !== null ? getA : false}>
      {(a) => <p>Counter: {a().b}</p>}
    </Show>
    ...
  </>
)
```

Now the question in my mind is should this be baked into Solid or left up to the user? Is there some way to have mechanics which work more like a component here?

**Comment by Koxiaet** [comment]
That solution doesn't work because when `state.a` becomes `null` the counter can be updated first which results in "Cannot read property 'b' of null"; this is the same behaviour as when `Show` is used without the callback. The order of updates doesn't seem to be deterministic so it only sometimes produces an error.

**Comment by ryansolid** [comment]
I mean to be fair I designed the function purpose. It doesn't need to be this way I thought it would be useful for specifically this case of having a "keyed" version when you wanted to replace everything sort of parallel to "For". Basically where you want to blow the whole thing away if `a` changes.  Otherwise there is no need for the function form.

```jsx
return (
  <>
    <Show when={state.a !== null}>
       <p>Counter: {state.a.b}</p>}
    </Show>
    ...
  </>
)
```

@Koxiaet That's a bug in this issue. I've got a fix I just haven't released it. #198

**Comment by rturnq** [comment]
@ryansolid Yeah, I think the current behavior of Show is fine and I'm sure makes sense in many situations. You just have to be careful if you plan to use the function form just to simplify accessing the value because you might end up re-rendering an entire component tree without realizing it. I assume replacing the whole tree is less efficient than fine grain updates. Consider the difference between

```jsx
<Show when={store.entities.details[props.entityId]}>
  {(entity) => <EntityDetails entity={entity} />}
</Show>
```
vs.
```jsx
<Show when={store.entities.details[props.entityId]}>
  <EntityDetails entity={store.entities.details[props.entityId]} />
</Show>
```
or
```jsx
const entity = () => store.entities.details[props.entityId];
<Show when={entity()}>
  <EntityDetails entity={entity()} />
</Show>
```

**Comment by Koxiaet** [comment]
I opened this issue because I thought that the callback form was the only way to use dependent data with Show, not realizing that it was only a bug that prevented the normal version. I'll close it since the normal form will work just fine for me.
