### ISSUE TITLE
setState Pathing, Ability to Evaluate Expression on Filter Results

### ISSUE THREAD

**Issue by Myrdden** [ryansolid/solid#220]
The syntax of setState is really awesome... However I've run into a bit of a hole, or maybe I'm just not using this correctly...

In a contrived but still related example, let's say I have
```jsx
setState('path', 'to', 'array', x => x.startsWith('abc'), ...
```
and then I want to update only the first result of that filter. Currently, it doesn't appear that there's any way to do this, as the filter function will then evaluate the next expression in the chain against each result, so trying to do something like
```jsx
setState('path', 'to', 'array', x => x.startsWith('abc'), 0, 'changed');
```
will result in the thing setting the key '0' on every result to be 'changed'... Maybe, without breaking the prexisting functionality which is more useful in like every other circumstance, something could be implemented, like maybe an object with a `where` key or something, that would evaluate the next expression on the results of the filter rather than on each result?

Or is this actually possible currently and I'm just not seeing how?

**Comment by ryansolid** [comment]
Hmm.. yeah fair I guess because it turns everything downstream into an iteration. I didn't think this through as much there is syntax where you can check the current path in the setter. I was thinking if you wanted only a single index you'd filter on that index as well. But I get you intend to act on the first filtered child and not index 0. Even my path would show the original index I believe. I think the challenge here is it becomes like an intermediate result. I almost would rather make the filter smarter. But the only way I can think of that right now is to store a temporary variable outside of the setter call. Even as a composable helper.

```js
let found;
setState('path', 'to', 'array', x => !found && x.startsWith('abc') ? (found = true) : false, 'changed');

or like:
function first(predicate) {
  let found;
  return (...args) => {
    if (found) return false;
    return found = predicate(...args);
  }
}

setState('path', 'to', 'array', first(x => x.startsWith('abc')), 'changed');
```

Not built in but just spitballing. I feel it is more that the filter is failing rather than needing to have intermediate results. Let me know what you think.

**Comment by Myrdden** [comment]
Well, that isn't really what I was going for... In reality, I'm essentially trying to update a dynamically assigned index, so the actual call looks something like
```jsx
setState('path', 'to', 'array', x => x.startsWith('abc'), index, 'changed');
```
where `index` is a prop, but in a more generic sense I'd imagine the from-to object could also be useful here... I'm picturing something like `{where: fn(), at: 0}` or `{where: fn(), from: 0, to: 5}` or something, that you could just shove in there to fill the gap without changing anything that's there already, granted I haven't actually looked at the source for this so maybe that's not possible...

**Comment by ryansolid** [comment]
To me it becomes less obvious what the behavior is especially since I reference things in paths (second argument to the setter function if used to the original location. I mean this is to streamline most setup. It isn't designed to handle every scenario (including many multi update ones).

This case is particularly strange in that without using ids you can look up you have to somehow map back to the original index after filtering. Especially if you are doing a full replacement at that index and not just modify something that is there. Because ultimately in state while you have say index 2 of the filtered results it might be actually index 47 you have to replace. That's really hard to do without IDs in almost any system.

It's:
1. Filter list
2. Find item at requested index
3. Find index of item in original array
4. Set newValue at that index

You can also just do the work outside:
```js
const itemToBeReplacedOrUpdated = state.path.to.array.filter(x => x.startsWith('abc'))[index];
const updateIndex = state.path.to.array.indexOf(itemToBeReplacedOrUpdated);
setState('path', 'to', 'array', updateIndex, changed);
```

I see your edit now:
>  why even use the filter if we're just passing indexes?
Yes I'm wondering that myself. I think this behavior could be wrapped in a nice way to generate a list of indexes to traverse but the mapping complexity is just nasty as the general purpose behavior. I'm sure this is solveable in a nice to wrap up way it's ok to do the work on the outside or do multiple set state calls in a loop (wrap them in `freeze` so they notify together). Truthfully I was pretty happy to have these short cuts but I'm already conscious of the code size it adds to everyone who doesn't even use these features.

**Comment by ryansolid** [comment]
In summary, the setState modes are extra helpers and not designed to solve every problem. There is always a way of solving these problems without having a baked-in syntax. I will leave this in userland for now.
