### ISSUE TITLE
Set Signal Function

### ISSUE THREAD

**Issue by Myrdden** [ryansolid/solid#223]
Hello, would it be possible to have signal setters take a function, like setState and memo do? I.E.
```jsx
const [getSignal, setSignal] = createSignal([]);
const push = (val) => setSignal(prev => [...prev, val]);
```
or something similar?

My gut is worried because it feels to me like doing `setSignal([...getSignal(), val])` would open up the potential for some infinite loops, and wrapping getSignal in untracked is a lot of typing... Also, I suppose as most of the other functions can do that, especially setState, it would seem to fit.

**Comment by ryansolid** [comment]
This has been suggested before. I'd love to support this. If you have an idea of how we can set a function? Signals can hold functions so it needs to be able to tell the difference somehow.

**Comment by Myrdden** [comment]
Ahh, yes... Well, functions can return functions...
```jsx
setSignal(() => fn);
```
This may be a total bodge though. Can't off the top of my head think of another way.

**Comment by ryansolid** [comment]
Yeah issues like that of object destructuring are not the type of things I'd like to introduce. Those are things that just stick with people and accidentally trip on them over and over even after they know. Very little I can do about that, but this I can.

The biggest benefit here is reducing potential for infinite loops. Self incrementing things in computations can spiral out of control. It isn't super common since most of the time we are setting in an event handler etc.. But it can definitely happen. Like if you were trying to count how many times some other event happens, or create a list history of values set in a signal. Although I wonder if there is a better way to catch these in dev mode.
