### ISSUE TITLE
Removal of afterEffects

### ISSUE THREAD

**Issue by Phillips126** [ryansolid/solid#236]
I noticed in the latest version (0.20.1), the `afterEffects` API was removed.

Was there an alternative solution added?  I previously handled some login/app setup functions on the top-most component when the component was first loaded (it is never unmounted - so it ran only once on initialization).

Is it safe to use something like:
```
const App = () => {
  const setup= () => {
    // handle setup/init stuff here
  }

  setup()

  return <div class="app">Hello World</div>
}

export default App
```

Thanks

**Comment by ryansolid** [comment]
Hi @Phillips126 what you are looking for is: https://github.com/ryansolid/solid/issues/225. I should have linked this right off the release notes.

The short answer is `createEffect` is what you are looking for, perhaps with `untrack`. In order to account for asynchronous concurrency and complications around `ref` handling I built scheduling into the reactive system now with effects executing after render.

**Comment by Phillips126** [comment]
Great, I appreciate you're quick reply!

**Comment by ryansolid** [comment]
To be fair it you don't read from the DOM ie using refs what you wrote would be fine as well as the component body only runs once.
