### ISSUE TITLE
Better way to sync computation dependent on props

### ISSUE THREAD

**Issue by SanichKotikov** [ryansolid/solid#247]
Hi,

I have a calculation function that dependent on props, and the result should be rendered by a component, and rerendered when props will change.

```ts
function calc(id: string, data: something[]) {
  return someResult;
};
```

There is a two ways: sync & async. In my case the computations are small and the sync one looks good.

#### The first idea

```ts
const [state, setState] = createState<Type>({});

createRenderEffect(() => {
  setState({ result: calc(id, data) });
});
```

But there is a small problem, I have to check if result data in state is not undefined before to use it for the render, or I have to use `{} as Type` in createState.

#### The second one

```ts
const getResult = createMemo(() => calc(id, data));
```

But in this case I have to call getResult function all time I need some values for the render.

There is the better/elegance way to do this computations and renders?

**Comment by ryansolid** [comment]
So I understand.

The first issue is a TypeScript issue since it can't tell it has been assigned inside the closure? Or simply we didn't initialize a value so TS thinks it could possibly be undefined? Is there a situation when you get to your JSX template that it is undefined?

I'm unclear what the 2nd issue. This is what `createMemo` is for. To cache an expensive calculation so it only is run again on update no matter how many places you use it. Is it you'd rather hide that it's a function call in some way?

What is sync & async? Everything I see in the examples are synchronous I think.

Side note.. `createComputed` is probably preferable to `createRenderEffect`. End user code should almost never need to use `createRenderEffect`. It is mostly internal and used for rendering. `createComputed` is designed for reactive updates and will run at the same time as `createMemo` before any side effects. `createEffect` is for post render.

**Comment by SanichKotikov** [comment]
Thanks for the answer.

Here is the full code https://github.com/SanichKotikov/solid-family-tree-example/blob/master/src/components/Tree/Tree.tsx#L27

> The first issue is a TypeScript issue since it can't tell it has been assigned inside the closure? Or simply we didn't initialize a value so TS thinks it could possibly be undefined? Is there a situation when you get to your JSX template that it is undefined?

It didn't initialize, cuz it actually happens in `createComputed`. So I have to use ugly `as any` or unnecessary `if (!state.tree) return null;`

> I'm unclear what the 2nd issue. This is what createMemo is for. To cache an expensive calculation so it only is run again on update no matter how many places you use it. Is it you'd rather hide that it's a function call in some way?

If I use `createMemo` I have to always call result function:

```ts
const getTree = createMemo(...);

<div
      style={{
        position: 'relative',
        width: `${getTree().canvas.width * width}px`,
        height: `${getTree().canvas.height * height}px`,
      }}
>
```

and it looks like an overhead (maybe only visual).

**Comment by ryansolid** [comment]
Alright. Yeah the TS issue is a thing. Similar to how much of a pain it is to construct an object a property at a time. I still struggle with this sort of thing with TS. I can't say I have a great suggestion there.

For the second example, it's a visual thing. It won't re-run your `calc` unless one of your props change. This is doing exactly what it is supposed to. Regardless of how we wrap things in Proxies we are effectively calling a function there. Calling a function is the cheapest version actually. I do have one option you might like especially if you have other state:

```jsx
const getTree = createMemo(() =>
  calcTree(props.nodes, {
    rootId: props.rootId,
    placeholders: props.placeholders,
  })
);

const [state, setState] = createState<IState>({
  get tree() { return getTree() }
});
```

**Comment by SanichKotikov** [comment]
The last example looks interesting, thanks 👍
