### ISSUE TITLE
[enhancement] SVG-capable Portal component

### ISSUE THREAD

**Issue by joshuafcole** [ryansolid/solid#259]
This is more of a feature request than a bug -- a few other `Portal` implementations I peeked at when I ran into the issue also don't handle this case, but it seems like an oversight.

Presently, the Portal implementation always uses a wrapping `div` node around its children. Unfortunately, foreign elements like `div`, when inserted under an SVG root, cause themselves and their children to be invisible.

There are a number of potential solutions here, the simplest of which being an `svg` boolean flag on the Portal's props that replaces the container with something like:

```
document.createElementNS('http://www.w3.org/2000/svg', "g")
```

If you're interested I'd be happy to submit a PR, though given it's only a few lines and a test case, that might actually be more time consuming for you rather than less!

**Comment by ryansolid** [comment]
Yeah that's true. I don't do component specific analysis so detecting SVG children ahead of time is no good. So I agree an option seems like a good idea. Is there any downside with an arbitrary element inserted in SVG?

I was trying to think if it was better to choose which element to mount but that doesn't necessarily inform how to create it without doing a lookup. I can do that, but it would be runtime instead of compile time so there would be overhead of pulling the list of SVG elements. The truth of the matter is if the Portal only had a single element child I could probably get away without inserting an extra element. But it's an unexpected arbitrary constraint.

Funny enough if I made the container accept JSX element then we wouldn't have these problems. But it's also strangely arbitrary. Like:
```jsx
<Portal mount={document.body} container={<g />}>
     .....
</Portal>
```
I'm not sure how I feel about that. It does solve my issue but it's like why isn't it in between the tags. Also it opens people up to thinking they could dynamically swap it I think and that is not fun. 

So I may be better off with what you suggested. Let me think about this a bit. And if you or anyone has any opinion on these options I'd like to hear it.

**Comment by joshuafcole** [comment]
> Is there any downside with an arbitrary element inserted in SVG?

That depends on the element, strangely. The only two real choices that I know of are the `<g />` tag and `<svg />` tag, because svg discards both non-svg namespaced elements and treats all other svg tags that I'm aware of as replaced. 

The `svg` tag has more of an impact than the `g` tag, as it specifies a new relative positioning context when nested. There are particular properties you can set (including via CSS) that would cause the `g` tag to change things like default style or transform origin, so it's _theoretically_ possible a regular user would write selectors that accidentally bump into that, but it seems pretty unlikely.

The only other problem I see actually applies to the normal Portal implementation too -- which is that if you're trying to do strict descendant / sibling selectors for some reason, you need to account for the hidden container element.

> Portal only had a single element child I could probably get away without inserting an extra element. But it's an unexpected arbitrary constraint.

Yeah, that seems like it would be frustrating too. Theoretically, you _could_ do away with the container altogether though, and inline the children into the mount by replacing container with an array, but besides the obvious performance hit to the normal case, I'm not sure what other effects that might  have.

> I was trying to think if it was better to choose which element to mount...

Mm, I considered that initially but it seemed like forking over more power than was warranted. That said, it opens up the Portal component to a couple other potential future use cases (which I don't believe have compatibile implementations for solid right now, so I didn't give them much weight): 
- something like React Native
- JSX driven Scene Graph libraries (like A-Frame)

> Funny enough if I made the container accept JSX element then we wouldn't have these problems. But it's also strangely arbitrary.

Yeah. This is the most flexible solution, but it lets the user dig some unfortunate ditches. For example, someone relying purely on intellisense without checking the docs might reasonably believe they were meant to put the `mount` target element into the `container` property and vice versa, with hilarity ensuing.

> Let me think about this a bit.

No rush! I just copied the existing Portal implementation inline and tweaked to suit temporarily. Thanks for putting so much care into the design of Solid!

**Comment by ryansolid** [comment]
Ok added `isSVG` boolean in Solid v0.22.3.
