### ISSUE TITLE
Solid Refresh (Universal Hot Module Loading)

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/solid#263]
I've made Hot Module Reloaders before but they've been specific to Webpack. I leveraged the loaders to rewrite the module exports. You can see this in [Solid Hot Loader](https://github.com/ryansolid/solid-hot-loader). But we need a better solution. Although the approach I took isn't that off the mark. Digging I realized that the required solution for HMR is more similar to React's Fast Refresh than what those libraries were doing before. So we can at least take that of validation and inspiration for a solution.

HMR in granular reactive libraries like this to my knowledge is unheard of. No one has ever solved it properly. I have an idea how to but because we track deps at runtime we do need to recreate the DOM nodes below or do a Re-Hydration of sorts. The problem is it would require a whole different type of hydration. In SSR scenarios you bank on things being the same. However, with HMR you are counting on things being different. In SSR Hydration cases you can write your code to trust the initial values (hardcoded, or serialized from server). In HMR you know they've changed.

 So it's probably saner to redraw the portion of the page. What that means though is we need to continue to wrap hot acceptors at each component module level so only views below the change are affected. In Solid Hot Loader it was manual. [React](https://github.com/facebook/react/issues/16604#issuecomment-528663101) has some better heuristics. And to make this universal we use babel to transcompile This is only the first goal.

I have been working on serializing the graph. So it should possible to restore data below the change point. BUt that will take further consideration.

**Comment by gixxi** [comment]
Zu rr

Von meinem iPhone gesendet

Am 15.11.2020 um 08:49 schrieb Ryan Carniato <notifications@github.com>:

﻿

I've made Hot Module Reloaders before but they've been specific to Webpack. I leveraged the loaders to rewrite the module exports. You can see this in Solid Hot Loader<https://github.com/ryansolid/solid-hot-loader>. But we need a better solution. Although the approach I took isn't that off the mark. Digging I realized that the required solution for HMR is more similar to React's Fast Refresh than what those libraries were doing before. So we can at least take that of validation and inspiration for a solution.

HMR in granular reactive libraries like this to my knowledge is unheard of. No one has ever solved it properly. I have an idea how to but because we track deps at runtime we do need to recreate the DOM nodes below or do a Re-Hydration of sorts. The problem is it would require a whole different type of hydration. In SSR scenarios you bank on things being the same. However, with HMR you are counting on things being different. In SSR Hydration cases you can write your code to trust the initial values (hardcoded, or serialized from server). In HMR you know they've changed.

So it's probably saner to redraw the portion of the page. What that means though is we need to continue to wrap hot acceptors at each component module level so only views below the change are affected. In Solid Hot Loader it was manual. React<https://github.com/facebook/react/issues/16604#issuecomment-528663101> has some better heuristics. And to make this universal we use babel to transcompile This is only the first goal.

I have been working on serializing the graph. So it should possible to restore data below the change point. BUt that will take further consideration.

**Comment by ryansolid** [comment]
I've begun work on this. https://github.com/ryansolid/solid-refresh

**Comment by ryansolid** [comment]
Ok I've gotten basic support now for most libraries. I will continue improvements in that repo. This issue has run its course. We have our base solution.
