### ISSUE TITLE
`each` nextSibling error

### ISSUE THREAD

**Issue by luwes** [ryansolid/solid#28]
Not sure if it's a biggie but a node seems to be undefined sometimes when randomly shuffling the list in each. Creates this error.

<img width="553" alt="Screen Shot 2019-05-17 at 5 44 31 PM" src="https://user-images.githubusercontent.com/360826/57957834-c4629500-78cb-11e9-9bad-44f150efcd9c.png">

Check the dev tools here, https://codesandbox.io/s/solid-list-shuffle-v41gk

**Comment by ryansolid** [comment]
Thanks for reporting this. Issue introduced when I added support for fragments a few versions back. It was failing swapping when the first element of the array since it walked backwards past the first element to null, then tries to move forward again. I've fixed this to walk backwards in 2 steps, so we get the second value before stepping back to null.

Fixed in 0.6.5.

**Comment by luwes** [comment]
Thanks for fixing!
