### ISSUE TITLE
Selective babel compilation using directives

### ISSUE THREAD

**Issue by aminya** [ryansolid/solid#286]
It would be awesome if there is a mode in the solid plugins in which a directive like `'solid-js'` informs Babel that this file is using solid-js and so it should compile it using solid. This mode should ignore other files that do not have this directive. 

This feature allows the incremental introduction of solid-js into a codebase that is already using other JSX libraries like React, etc.

I have written a babel plugin like this before (for other purposes). If you are interested, I can make a PR to help with the implementation.

https://github.com/atom-ide-community/babel-plugin-transform-not-strict

**Comment by ryansolid** [comment]
Are you suggesting like a comment at the top of file? To date Ive relied on bundler rules(webpack, rollup, parcel, snowpack, etc..) to do this. I do know JSX has the pragma approach but thats more about selecting provider rather than whether it be processed. Only other thing to keep in mind solution probably couldn't be Solid specific and need to work with other DOM Expressions libraries.

**Comment by aminya** [comment]
> Are you suggesting like a comment at the top of file? 

We can support comments too, but I prefer a directive. Something like the following at the top of the file:
```
'solid-js'
```

> To date Ive relied on bundler rules(webpack, rollup, parcel, snowpack, etc..) to do this

If using babel itself alone, I think there is no way to do this.

> I do know JSX has the pragma approach but thats more about selecting provider rather than whether it be processed. Only other thing to keep in mind solution probably couldn't be Solid specific and need to work with other DOM Expressions libraries.

But does solid-js uses JSX pragma? My understanding is that solid-js has a special transformer plugin which is different from other types of JSX libraries. That's why I am suggesting a special directive like 'solid-js' or 'use solid-js'.

If you prefer a jsx pragma at the top of the file, we can use something like the following:
```
// @jsx solid-js
```

But we should be sure to process that file before other JSX transformers, as `// @jsx solid-js` has a special meaning.

**Comment by ryansolid** [comment]
Ironically for TypeScript, we support the `/* jsxImportSource solid-js */` which we need so that we can play nice with multiple JSX types when in projects with React etc.. Generally, we just put it in the tsconfig and not per file but I wonder if it makes sense here since you'd be opting in for similar reasons (ie. React in the same project).

What I meant about DOM Expressions is technically the Babel JSX compiler we use isn't unique to Solid and used by several libraries. But I guess we could do something like give it an option to set what the pragma would be and only process those files if the option is provided. In absence we'd continue to process everything (the default as I don't think people should have to write something per file). And then in Babel Preset Solid we could have an option like (`pragmaOnly`)  that would set the right one.

I guess your concern is the collision with other JSX compilation as well. Do the standard React ones have a way to opt-out of processing them? The awkwardness is we need for things like TypeScript follow the standard Babel conventions even when not using the standard transformer. So it feels like we need to follow suit here as well unless we expect devs to be adding multiple things to the top of their files. I'm not sure we could guarentee precedence. The end-user would have to put them in the right order which might be a bit fun with presets vs plugins etc...

Thoughts?

**Comment by aminya** [comment]
What I meant originally was an option like `directiveTrigger: false | 'solid-js' | 'only not solid-j'` that allows us to mention which file is (or not) using Solid. I did not mean this to be a default mode. 

The reason this is useful is when some big project is using other libraries, but they want to start replacing those with Solid. One way is to maintain two build systems to build the files separately. But this can make a lot of headaches. 

The easier option is just to set `directiveTrigger` to true in `babel-preset-solid` and then it only processes those files. 

```ts
directiveTrigger: 
	false  		// processes all the files  -> default
|	'only'		// only process those that have 'not solid-js' trigger
| 	'only-not' 	// only process those that do not have 'not solid-js'
```

**Comment by ryansolid** [comment]
For sure. I'm following the use case I probably wasn't clear enough in my response. I was only thinking of `false` and `only`. I didn't think of the `only-not` mode. That does seem useful but for the reasons below probably not the way to go.

I was saying that if that project was using TypeScript the pragma's would have to be there if they want to have both versions of the JSX since there is no other way to have 2 JSX TypeScript frameworks play nice with each other.  Like if you have Solid and React in the same project you need to put `/* @jsxImportSource solid-js */` at the top of your files or they will assume the types are React even if we are not using TypeScript to do transforms.

React Types screw everything up. It's the only way per file to get the right types. So I was thinking that any modern TS project that had both in it would have to be using that for Solid anyway, and might as well extend that to JS projects too. 

Which is why introducing another system seems awkward. But the problem is can we rely on preset order to ensure the right transformations. Like if our preset is last it will execute first. I think that is probably a safe bet. The only other challenge as I said is that the underlying babel plugin which I'm gathering is the thing we'd have to change isn't Solid specific. So the options would have to be something like:

```js
importSourceRequired: false | string // name of your library ie "solid-js"
```
This doesn't give us `only-not`, but it works with the other mechanism.. and we'd have to check for @jsxImportSource pragma's.

How does that sound?

**Comment by aminya** [comment]
That sounds good to me. Consistent API between TypeScript and Babel is a good approach that can simplify things even more.

> This doesn't give us only-not, but it works with the other mechanism.. and we'd have to check for @jsxImportSource pragma's. Unless there is a way to do this at the preset level.

It is OK with me. That was just a suggestion.

>  I assumed we'd have to add this check at the program visitor in the AST transformation of the plugin itself.

Yes. We can use an implementation of comment checking from here:
https://github.com/atom-ide-community/babel-plugin-transform-not-strict/blob/09df2d75bda9c56bb4b8abf0bc25f7c64a0e9039/src/index.js

```
            if (commentTriggers && commentTriggers.includes) {
                if (sibling.leadingComments) {
                    let foundInLeadingComment = false;
                    for (const leadingComment of sibling.leadingComments) {
                        if (commentTriggers.includes(leadingComment.value.trim())) {
							
							// do transformations

                            foundInLeadingComment = true;
                            break;
                        }
                    }
                    if (foundInLeadingComment) {
                        break;
                    }
                }
                if (sibling.trailingComments) {
                    let foundInTrailingComment = false;
                    for (const trailingComment of sibling.trailingComments) {
                        if (commentTriggers.includes(trailingComment.value.trim())) {

							// do transformations

                            foundInTrailingComment = true;
                            break;
                        }
                    }
                    if (foundInTrailingComment) {
                        break;
                    }
                }
            }
```

in which commentTriggers is `false` or `@jsxImportSource solid-js` pr `* @jsxImportSource solid-js`

**Comment by frenzzy** [comment]
@aminya have you considered adding a `.babelrc` file into a specific folder with solid components to override the babel behavior or use the `overrides` section in the main `babel.config.js` file? I.e. for example you can apply JSX transformations for `solid-components/**` or `**/*.solid.js` files only.

If you already knew about this possibility, why would you prefer the directive approach?

**Comment by aminya** [comment]
@frenzzy Instead of maintaining a list of files, I prefer the files to be self-contained.

 Some of the other libraries like Vue and Svelete define their own file extension to specify which files are using their libraries. But fortunately, Solid just uses JavaScript/TypeScript, which allows using all the tools that rely on the file extensions. 

Additionally, as mentioned before, when you open a file in your editor, if you don't mention somehow that this file is using Solid, the TypeScript types will be wrong.

**Comment by ryansolid** [comment]
Added the ability to restrict based on the pragma in v0.24.0.

**Comment by aminya** [comment]
Awesome!
