### ISSUE TITLE
Question: why is using a property inside a style object not updating my component?

### ISSUE THREAD

**Issue by romgrk** [ryansolid/solid#291]
Hey,

I've been playing around with solid and here is something I don't understand. In the code below, `props.progress` is a state value passed from above. When that value changes, it is updated everywhere except inside `style={{ width: props.progress }}`. I don't understand why it's not updating there.

```js
function Button(props: ButtonOptions) {
  const disabledValue = Boolean(props.loading || props.disabled)

  return (
    <button
      class='Button'
      disabled={disabledValue}
    >
      {props.children} {props.progress}
      <Show when={typeof props.progress === 'number'}>
        <span
          class='Button__progress'
          style={{ width: props.progress }}
          width={props.progress}
        />
      </Show>
    </button>
  )
}
```

Thanks

**Comment by romgrk** [comment]
After playing a bit with the example, it seems that adding `+ 'px'` so that the code is `style={{ width: props.progress + 'px' }}` makes the component update when `props.progress` changes. But I still don't understand why.

**Comment by ryansolid** [comment]
Oh ok, I was just about to look into this. Yeah, I probably should make a note more of the consequence of the approach we are taking here. Solid compiles to `el.style.setProperty` which is the most performant way to set a style property. This allows some cool things like setting CSS vars etc, but it means that the styles need to resemble the style string.
 
See https://github.com/ryansolid/solid/issues/143 for more details.

**Comment by romgrk** [comment]
Oh ok, so it is updating but `setProperty` ignores it because a number (except zero) without units isn't valid, right?

If so, it would be good to note it in the "Styling" or "Comparison with other libraries" documents, because react & copycats usually accept numbers as meaning `number + 'px'`. Is there any chance that this kind of thing can be handled by the compiler eventually?

**Comment by ryansolid** [comment]
Yeah Preact definitely does do the transformation. I don't think Inferno does. It could be checked at runtime but not at compile time. We can't tell if the `px` is there or not because the user passes a variable that could contain anything (including the `px`) so I can't just assume it's not there or there. No reasonable analysis would work for all cases consistently.

The Preact approach seems to use a matching pattern with a regex. It's sort of unfortunate overhead that would have to paid by all. It is worth consideration but this sort of thing is extra overhead just to bring this in line.

**Comment by romgrk** [comment]
Right :/ Sucks that it's not possible to use type information to solve those kind of issues, but I certainly wouldn't want a regex in there.

You can close the issue unless you wanna keep it as a reminder to update the docs.
