### ISSUE TITLE
Custom Environment Variables?

### ISSUE THREAD

**Issue by thatcort** [ryansolid/solid#292]
Does create-solid-app support custom environment variables like create-react-app does? In create-react-app any variables with names beginning with REACT_APP_ are substituted in during build. Is there a similar SOLID_APP_?

**Comment by ryansolid** [comment]
To my knowledge the SOLID_APP_ prefix should work. I did the migration in one big sweep so I might have missed a couple things but it looks like I did that one: https://github.com/ryansolid/solid-scripts/blob/master/config/env.js#L64

Let me know if that works for you.

**Comment by thatcort** [comment]
That works. Thanks!

**Comment by darrenbarklie** [comment]
Coming from Webpack/React to Vite/Solid, I learned of a couple of key differences in implementing env vars:
- No need to manually install dotenv package
- `.env` file should prefix variables with `VITE_`, e.g. `VITE_API_KEY=123`
- Frontend should access with `import.meta.env`, not `process.env`, e.g. `import.meta.env.VITE_API_KEY`

Worth skimming the [Vite env documents](https://vitejs.dev/guide/env-and-mode.html#env-files) for complete understanding.

Note that `SOLID_APP_API_KEY` alone returned `undefined`, necessitating a `VITE_` prefix.

**Comment by ryansolid** [comment]
Yeah thanks for adding this. The question was talking about the previous starter we used pre 1.0 which is long out of date. So the original answer no longer applies.

**Comment by christhornham** [comment]
@darrenbarklie Thank you!

**Comment by aronmal** [comment]
I think this should be mentioned or referenced in the docs. It was unknown to me or I expected the `VITE_` perfix only to be necessary for non api routes (semilar to how the next.js [`NEXT_PUBLIC_`](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser) prefix is being handled). I now found out myself and only after that stumbled over this issue here.
