### ISSUE TITLE
Tailwind Instructions?

### ISSUE THREAD

**Issue by thatcort** [ryansolid/solid#298]
I realize this may be out of scope for the library, but I'm trying to set up Tailwind to work with Solid-JS and not sure how to go about it.

Since solid-scripts seems to be based on react-scripts, I tried to mostly follow the Tailwind React instructions and use Craco to configure it as a PostCSS plugin. That didn't work, since Craco v6 complains that create-react-app is too old and Craco v5.8 complains that it `Cannot find ESLint loader (eslint-loader)` despite setting `eslint { enable: false }` in the Craco config.

Adding @amoutonbrady since I saw them mention using both Tailwind and CSS in another issue.

Maybe there's a simple way I'm missing? Any help appreciated!

**Comment by parlough** [comment]
I don't have experience using solid-scripts, but I found success using https://github.com/amoutonbrady/solid-snowpack-starter. It worked for me out of the box :)

**Comment by ryansolid** [comment]
Hmm.. yeah I forked off Create React App May 2019. I am not terribly familiar with how it's changed since then. Mostly was just looking for an easy starter toolset. I can't say I've ever tried Craco, I'm not even sure if the way I changed it would be compatible. It is sort of an as-is experience mostly. I did recently update PostCSS so I assume there must be some play here, but I'm not sure. Have you tried manually adding es-lint loader to your project? Obviously it isn't in our webpack config, but Craco seems to be trying to do something with it. Outside of that I am not sure what I'd need to do for Craco to recognize it.

Generally if you want more configurability we are sort of left with ejecting or using one of the other starters, since as you can imagine there isn't a community around modding this. In all honesty at some point I hope to be able to provide a better easy startup environment, but this was one I knew to atleast have all the standard niceties even if it is not that configurable.

**Comment by thatcort** [comment]
@rynansolid I'm using typescript, so I don't think ESLint makes sense, but also don't have much sense of what Craco or the starter scripts are doing. I can try adding ESLint as a dev dependency and see what happens. I think the main thing is figuring out how to allow the PostCSS config to be extended by the app, which really shouldn't depend on ESLint at all.

@parlough Thanks for the Snowpack starter link. I'll have to check that out. I see a tsconfig file, so hopefully that means it supports Typescript(?). This might be the easy path :)

**Comment by ryansolid** [comment]
My understanding is TSLint is being deprecated and ESLint with TypeScript presets is the future but yeah. I think for custom configuration you are probably better off on a different path. We're still trying all the tools and trying to find the best core build setup. I'm still very much on basic Rollup setup (but I don't care about DX at all in my personal setups) but @amoutonbrady  has been trying a lot of stuff. I used the snowpack build a bit and it was good for dev, but I'm unclear on how the prod build is. To my knowledge it supports TS, so you should be good.

**Comment by high1** [comment]
@thatcort, TSLint is depreacted for a while now, and ESLint only makes sense. https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by thatcort** [comment]
Thanks, @high1. I got things working using the Snowpack starter. I agree this is tangential to Solid, but webpack and create-react-app are outside my experience. I hope I'm not taking advantage of the community here by asking these questions.

**Comment by high1** [comment]
Nope, not at all IMO - the issue here is that the ecosystem is not nearly as vast as the other major ones, so a lot of questions don't have answers ready when you search... The starter uses CSS Modules with Tailwind, which I find problematic, because stylings are kept in two different places and I'm aiming to replace that with https://github.com/callstack/linaria - it should just work with Solid, because there's no runtime.

**Comment by russelgal** [comment]
@thatcort consider this solution https://github.com/tw-in-js/twind

**Comment by high1** [comment]
My personal preference is not to use CSS-in-JS with runtimes, because of the additional performance penalty - that's why the starter use PostCSS build step and will use Linaria.

**Comment by ryansolid** [comment]
I think this has run it's course.. but good info shared. Thanks everyone.
