### ISSUE TITLE
Bug(solid-element): duplicate content after re-connect the custom element

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#301]
This bug is easy to reproduce with the [example](https://webcomponents.dev/edit/yGRb00wV4AMncPupRmA9)

just select the custom element, remove it, and re-add it to the dom (by js or by `cmd + z`), the content will be doubled.

![image](https://user-images.githubusercontent.com/3808838/103689676-98c77d80-4fce-11eb-9b17-98071312d54f.png)

**Comment by ryansolid** [comment]
Thanks for the report. In all honestly since it never happens in normal flow I didn't think about what would have with attach/detach. I can clean up the old DOM nodes but since it's my only indicator that the component will be disposed it's where I've been doing my cleanup. I hope that is ok. Essentually detaching and attaching resets it as if is a new component. Except the element would keep any internal state not set by Solid. I'm not sure this is particularly great but I'm not sure if there is a better way if I want to handle not having memory leaks in a generic way.
