### ISSUE TITLE
SSR esm support

### ISSUE THREAD

**Issue by chrstntdd** [ryansolid/solid#309]
I tried to go through the steps to get the streaming ssr example in lts (14.15.4) and I'm unable to resolve the `renderToNodeStream` export which I think makes sense. This is a slice of exports field:

```json
{
 ".": {
      "server": {
        "import": "./dist/static.js",
        "require": "./dist/static.cjs"
      },
      "import": "./dist/solid.js",
      "require": "./dist/solid.cjs"
    },
    "./web": {
      "server-async": {
        "import": "./web/dist/server-async.js",
        "require": "./web/dist/server-async.cjs"
      },
      "server": {
        "import": "./web/dist/server.js",
        "require": "./web/dist/server.cjs"
      },
      "browser": {
        "import": "./web/dist/web.js",
        "require": "./web/dist/web.cjs"
      },
      "node": {
        "import": "./web/dist/server-async.js",
        "require": "./web/dist/server-async.cjs"
      },
      "import": "./web/dist/web.js",
      "require": "./web/dist/web.cjs"
    },
}
```

The bundler I'm using does not seem to comprehend the nested fields within each of these keys. I amended the exports field to include a separate sub-path:

```json
{
 "./server": {
      "import": "./web/dist/server.js",
      "require": "./web/dist/server.cjs"
    },
}
```

which lead to usage like so:

```
import { renderToNodeStream, generateHydrationScript } from "solid-js/server"
```

Is adding this subpath something that can be supported or am I missing something? Happy to make a PR.

**Comment by ryansolid** [comment]
I mean it's fine but also gets in the way of the code being isomorphic. I have server versions of both solid-js core and web. We can export it that way and then use the bundler to alias back. My main reason for going this way was to not have alias every random library that takes advantage of this. I'm in the process mind you to only having a single SSR approach and just using the "node" keyword which should simplify this setup.

So directionally I'm trying to get away from having a specific server export. Obviously problematic if tooling has issues. So I'm interested in what bundler you are using? I've only used Rollup here and node (you can choose not to bundle Solid (set it external) and just pass --conditions=server to the node cmdline if in the latest Node 12 or 14. My understanding was Webpack handled this fine but I haven't tried it.  I needed to make a PR for this with Snowpack although I think it got held up in the release after merging because they were having other issues with the node-resolve plugin. So I'm definitely interested in getting this sort of thing working properly.

**Comment by ryansolid** [comment]
Any updates? I'm interested in what bundler is giving issue. Directionally I'm trying to head this way but I do want to make sure we account for the tools commonly being used.

**Comment by chrstntdd** [comment]
Apologies for the delay. I was able to get things running with that `--conditions=server ` when I run it now. Got esbuild bundling the node server for ssr, consuming the `ssr` output using rollup. The dev setup I have uses nodemon and I can't quite get that option configured correctly is my last hurdle. Hadn't heard about that option flag. Thank you for the insight!

**Comment by ryansolid** [comment]
Awesome..It's all very new but it is a game-changer for handling exactly this sort of scenario. In the future this will work even without the option as node respects "node" condition and I'm working on consolidating all the SSR methods into a single approach.  Glad to hear you are getting this working. I intend to have better instructions and examples soon, but first I need to finish the core library work.
