### ISSUE TITLE
How to **subscribe** to a state/signal outside a solid component?

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#315]
`createEffect` is convenient inside a solid component, but to watch the change of a state/signal outside a component, I have to create a  root with `createRoot`, which is overkilling. 

Is there a way to subscribe to a state/signal outside of a solid comopnent?

**Comment by ryansolid** [comment]
The short answer is `createRoot` isn't overkill. Solid's primitives are missing parts since they are designed to work in a system. `createRoot` adds those back. `createRoot` handles the disposal properly, and ensures scheduling since effects need to be queued after other changes, so it creates the queue, and runs it at the end synchronously. Why does this matter? Well stuff like managing lifecycle hooks (ours are not tied to the DOM but rather reactive graph resolutions). This is especially important for Suspense and concurrent rendering. Like if your signal update causes a suspended transition should your subscription fire immediately or wait to resolve with all other side effects.

So while I'm tempted to point you to `createComputed` which would "work" without all this and is what you think you are looking for, it's probably better we think about creating a helper for this. The most idiomatic would be:

```jsx
function subscribe(fn, callback) {
  let dispose;
  createRoot((disposer) => {
    dispose = disposer;
    createEffect(() => callback(fn()));
  })
  return dispose;
}

// somewhere:
const dispose = subscribe(() => state.data, (data) => { console.log(data); });
dispose();
```
This would be concurrent rendering safe and lets the subscriber manage disposal properly. I use a similar helper in `solid-rx` to interface with Observables. This executes immediately on subscription. If you wanted it to only be on change you'd need to change it to not call the callback the first time.

**Comment by zhaoyao91** [comment]
@ryansolid thanks for your answer, very helpful :)
