### ISSUE TITLE
[Question] naming convention: `create` or `use`

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#317]
When creating utils such as `autoEffect`, I am confused what word should be used, `createAutoEffect` or `useAutoEffect`?

In react word, all hooks are prefixed with `use`, but in solid world, the prefix seems to be `create`. But there is a exception, `useContext`. 

So what does the `use` mean in `useContext`? Is there a guide about naming convention for solid tools/utils?

**Comment by ryansolid** [comment]
Generally we use `create` because things are only created once in Solid. Unlike React where each time through the render they re-use the hook if available.

I do use `use` in a couple primitives because they aren't `create`'s. In the case of `useContext` there is a `createContext` already that actually creates it. So `use` there is to indicate you are using the already created context. The other is `useTransition` this one might be better as a create other than the fact it doesn't create the `transition` but rather the thing it returns does. So it's more like `createTransitionCreatorFactory` but `use` seemed to fit the bill as well. This one is definitely is newer and experimental so it's up to some debate whether that is the best API name for it.

As for a guide I don't have anything for that as of yet. It's an interesting question. And could serve as a basis for linting. It's also already even more of an opinionated stance to take so I also wonder how much of that should be doctrine.

FYI Our discussions section is a great place to ask questions like this in the future since it will be kept organized for all time for others to see. I would move this issue over now, but Github has temporarily disabled this (it's been like 2 weeks). So we will leave this here but just a thought.

**Comment by ryansolid** [comment]
Yeah github is still not bringing back the feature. I will just close this for now.

**Comment by birkskyum** [comment]
I'm on team `use` for solid. if we're to have people migrate over millions of apps, it's for the better to just have the same syntax, especially with other signal implementations like vue and svelte5 converging there too.
