### ISSUE TITLE
JSX type definitions

### ISSUE THREAD

**Issue by bluenote10** [ryansolid/solid#33]
I'm still assessing Solid's Typescript compatibility and I noticed that there are no type definitions for e.g. `JSX.IntrinsicElements`. This prevents using Typescript in strict mode, in particular it enforces to allow implicit any. 

In strict mode the following fails to compile:

```js
import { createRoot } from 'solid-js';
let el = document.getElementById('root')!;
createRoot(() => el.appendChild(<div>Test</div>));
```
Error at the `<div>Test</div>` expression: 

```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
```

To solve this I think we need definitions similar to [these](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21e68259f6fd43aba37e8112e3edb792975f8266/types/react/index.d.ts#L2829-L3007) for React.

**Comment by ryansolid** [comment]
These are in the babel JSX plugin right now. It seemed the current logical place since not everyone uses JSX with Solid and more than just Solid uses this JSX dialect. 

We are just in the process of writing up the documentation of how to use them. There is a bit of a gotcha with control flow since Typescript doesn't allow $ from being an intrinsic element. So I'm still very much open to suggestions of best practices as I'm new to Typescript myself.

**Comment by bluenote10** [comment]
Thanks! Adding the plugin to the type roots did the trick:

```
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/babel-plugin-jsx-dom-expressions"
    ]
  }
}
```

**Comment by thatcort** [comment]
I just ran into this issue in an install of the create script. Adding the plugin to the type roots doesn't help -- I don't see any type definitions in that module.

The error I see in VSCode is the original one mentioned above: `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`

Has the suggested solution changed since this bug was fixed?
