### ISSUE TITLE
[question] use Component name instead of JSX syntax

### ISSUE THREAD

**Issue by samadadi** [ryansolid/solid#352]
I have a simple Switch with multiple Match in it and as the fallback I use NotFound function component. So when I use JSX syntax, everything is OK but when I use just component name, there is an error.

with JSX syntax:
`<Switch fallback={<NotFound></NotFound>}>
...
</Switch>`

 Compiles to a getter function & everything is OK.
` get fallback() {
      return createComponent(NotFound, {});
    }`

without JSX syntax:
`<Switch fallback={NotFound}>
...
</Switch>`

Compiles to the following form & throws an error.
` fallback: NotFound`

**Update**:
Actually It is working but there is another component inside NotFound component that uses a function from context provider but that function is undefined and that is why It throws an error. As I said It is working with JSX syntax.

**Comment by ryansolid** [comment]
I don't see an issue with the compilation. If you pass an identifier it will assign it. After all it could be a string or some other value.  If it is a function accessing it on the props won't execute the function immediately. However if inserted in JSX it will eventually be executed, but this isn't desirable as it treats it like a reactive expression rather than a component.

Generally you should use JSX syntax here. Create component call isolates reactive context. But for understanding purposes, this is closer to being equivalent.
```jsx
<Switch fallback={NotFound()}> ... </Switch>
```
You can view JSX component syntax as a function call instead of a declaration.
