### ISSUE TITLE
Question regarding solid-element

### ISSUE THREAD

**Issue by mcjazzyfunky** [ryansolid/solid#367]
First, thank you very much Ryan for this extremely interesting and smart Solid project.
And also many thanks for your equally interesting blog posts regarding Solid etc.

If have two questions:

1. Is the github issue tracker even a proper channel to ask questions regading Solid or do you prefer other channels?

2. Regarding `solid-element`:
   Is it somehow possible with `solid-element` to write a function
   ```ts
  
   declare function define(
     tag: string,
     componentType: ComponentType<{}>)
   }:  () => JSX.Element<{}>
   
   declare function define<T>(
     tag: string,
     props: PropsDefinitionInput<T>,
     ComponentType: ComponentType<T>
   ) : (props: Partial<T>) => JSX.Element
   ```
   
   which has the same arguments as `solid-element`'s function `customElement` but a different return type (not really sure whether the above typing is 100% correct, anyway....), which would allow the following:
  
   ```jsx
   // using JS here to keep the example simple, but this is
   // nevertheless primary meant to be used with TypeScript
   
   const Counter = define('my-counter', () => {
     const [count, setCount] = createSignal(0)
     const onClick = () => setCount(count() + 1)
     
     return (
       <button onClick={onClick}>
         Counter: {count()}
       </button>
     )
   })
   
   const Demo = define('demo-app', () => {
     return (
       <>
         <Counter/>
         <hr/>
         <Counter/>
       </>
     )
   }
   ```
   
   This would be nice in several ways:
   
   - Doesn't really look like a webcomponent app
   - Type-safety out of the box (even without extending JSX.IntrinsicElements)
   - You have to take less care about (too much) tree-shaking
   - etc.
   
   With a virtual DOM library that would be quite simple:
 
 
   ```js
   function define(tagName, ...): ... {
     // [...]
     
     return createVElement.bind(tagName)
   }
   ```
   
   Please find here a little demo of a virtual-dom-based webcomponent library that uses a factory pattern instead of Solid extremely nice "render once model".
   Obviously the R&D fun library in the example would be much nicer when using Solid internally.
   
   https://codesandbox.io/s/fancy-sunset-g7ho0?file=/src/index.tsx
   
 Thanks a lot in advance.

**Comment by ryansolid** [comment]
1. I've been pushing stuff towards Github discussions. Discord is still the best place to get a quick answer but I like that the discussions create a record and help others. This repo isn't popular enough that getting questions in the issues is really a big deal, but I'm trying to keep issues to bugs, and agreed upon feature development.

2. This is possible I believe this would work:
```jsx
import { spread } from "solid-js/web";

function define(...args) {
  const CustomElement = customElement(...args);
  return (props) => {
    const el = new CustomElement(); // could also be document.createElement(args[0]);
    spread(el, props);
    return el;
  }
}
```
Biggest downside of this approach is that we need to immediately go to use `spread`. Spreads are always a bit of a de-opt as they lose granularity of update, cannot be statically analyzed, and pull in a mainly runtime routine. It also breaks the template that we clone apart too. So instead of creating all the elements in one go the way you would native it would create these separately. Those both aren't the biggest deal though and aren't any worse than say Styled Components.

**Comment by mcjazzyfunky** [comment]
Many thanks, Ryan. Working as you have described above :smiley:
Solid is really a great library!

BTW: Seems `component-register`  currently lacks a bit of proper attribute handling (converting attribute value to prop value and vice versa etc.), but I guess that's already known.

**Comment by ryansolid** [comment]
> BTW: Seems component-register currently lacks a bit of proper attribute handling (converting attribute values to prop values and vice versa etc.), but I guess that's already known.

Not to my knowledge. I used the library with Knockout for several years in production at my previous company. Generally better off setting props, there is some configuration options to change how it handles, and I probably should document more. Generally speaking if you set the attribute all I can do is JSON.parse it.. https://github.com/ryansolid/component-register/blob/master/src/utils.ts#L114

So that should all work although there might be a camelCase/dash-case transformation back and forth happening. We made some interesting changes to how Solid handles things which might be causing confusion. Generally for custom elements always set the props even if written like an attribute. But it does an auto camel-case conversion. So generally if you are using things in solid you should aways be writing dash case and using camelCase in your props..

Like
```js
<my-element some-field={state.user} />

function MyElement(props) {
  props.someField
}
```
So for the most part it never sets attributes so complex stuff should pass through no problem with no transformation... There are some ways to force attribute and property handling using namespaces but the JSX types don't work right  yet and TypeScript itself doesn't work with them until 4.2.

Do you have a specific example of a transformation problem?

**Comment by mcjazzyfunky** [comment]
Hmmm, okay, thanks for the info ... nevertheless some things feels a bit odd (at least for a Solid rookie).

Please have a look at the following demo, which uses the web-component fun library that I was already using in the demo above (like said this is a virtual dom based custom element library):
https://codesandbox.io/s/fancy-sunset-g7ho0?file=/src/index.tsx
Everything works as you would expect even without knowing details about this toy library.

Now please have a look at its Solid counterpart (sorry, this is actually working on the Solid dev server but not on the Solid playground, I do not why 🤷‍♀️ , but read the comments in the last few lines and you will understand the issues):
&raquo; [Solid Playground Demo](https://playground.solidjs.com/#NobwRAlgJmBcYA8BsBrArAJwMYIAwCsAWCXNAdwCYBPAByQDsAjAWwHZmwAaMegQ2YCmcMM14R6XMABdaQ+FIDOCSQoD2AV2xzIzGqoxSABCEOCMAcwEAFDKpoLOhgFIBlABqOsGAbykCXUr4ChgC+hgBmtsyGAORqADbQALT4CjEAOvQQuvpGJgo03rxQoRFRsQnJqQD0ZAKMGVk5BsaGWOoKUqrMAKLxAoL0Uo4Awt169AJDACqypZHdFaqJUEkC-YNSjdl6LSY2dgoAIgLh4hBSEKr0AJL0NOpGYQvRMVjj11NSSd7mEJ0CDCNTLVaqGAC8kMMAEErDcIZDEUjkSjUWj0RikZlMuF1PQsJdroYoKdxAIABSBcwAOX4Alghk6GHE5kc4XoDLGOUmM1kAB4QCEAHwASgZ5JFEKFzncADo+gMvtj6Lj8YT6MTSZM+dMheTMoZDFSGUyWZwDYZCocGQd7Cczll1XcHlIdULzRrDFyJl9ZjR6V6PjypH6BG7MmLDOSrfYbbwDBBePE3ZLwdLXG55RslfQcXiCVcNSSHRSLVTaYITVJmfRWRb4+YKAzePQqB7DQ2AMwAfmbrYj4pjCj7VFT6blCs2xgtEHCUZk-tUc4bFAR4NiqoL1xikpAFsN7U63UnX0pvBpdMcgscK5FysNhu8Uk0GolUuJqnam1lXh8fhPQxnhegh3p6IT3m0HRdL02aAeWl6GCuN4WJ2oEWk+L5RkOI5jtOnoHtcnSGOsAwQh+X5fD+RT-rBUhARWAhofhjKFD4UDkiRzCOEOoEPoYGEYBqnEWuB9CiXmaqFoYHQCPavDqPEih8lYxEIH49BQAohgAEoCO8GBQHypq1jerbuoYRyqepmmGFY8aXEmylCnqFrYbZ7aauE8mKcOFkDrZhgAGQWXhj4CM+gmmICli2go5LFt5ijcbY9igeJKr5uq0kKP4gR+HyLhWVMNm6fphnGayiFmXqnRBAyLi7uh4WYb+QQBEE5K1X4aXKpuWXeBpgLku8QxfAyGZZoqQyGAAPoY9AKfEjiBBY4UuCRBL6FWNbmI1nojURK2WEY65QJ+6jfgAjuogJUOt-SbRgZ6rVI916V0GBMYas5RgAhEd4V7XxUgABa2GQ80CBDPQYLYT0xMAA0khgAC6gYKSU9CqEYDolADRicV8O4iRB+OyuIkwYAAEtMACyAAyZExMCno-cN1zqVIQMPmTvA0P6GkjCDEDxOxI2c4hWk0wzAFcyTYnKqCa6mGIGqYurGua2iyoHUY7x4n4GCxfaZF7qzjqJvEYwGwyZt8QAbkmN0MrgHkdlI1YQIwjwBjE5wOfEST60MMRu-N2OzlQDJefEOUiR6FrxLwjDrLb+6GI78TO7E1ujUCYe+J73t+AyMRJyn8Sh+nWOXOEUcREmcdgZk6W6+jedkcWZLkjEzBUEHGh56HbSD4bxunI40YpQouF2yP9BETQZEyXJCmKFPhxXoY-uW7nUgu445epzno+AjEoS8fPRHAA4jLhWj64ye1fjkiYwf75a5MW0me8XxabfXBGIkLAKAyJvjTHfOibxR7D3JBcXCFxDAAGpDAAEYvr8WapFfUzE+TFy6BqQBwCUDghAEQiAIDhTp0NCAIcsoj7xBCLbBQP5R6iT4nyao+DrhCgtGlJiZ0KJDFlMdWWAAhKgNx2IxD5jQHcv0v6U2lozdcAADC0NdDBkH0CgFkFo+RQAgPbbeUBwTpDALI1B5ihScMMfbXhno+RgwcYaTR2iMC6NrPouxJizEWP5hQaxtijEuMME4jAoT3GePMN4oxvjzGyM7EE6odjQnhMiTovRjifHQD8bIwgyTUmZHUbmegStQb-G3lpakAB5aYWjMm1kMEkRkINVBkC0i2be394gjwNoYJchhcDdIBMUAZc5UG4FwJkJGQ0+R70BN0i4u9R6kMmbgMI1RzIxAAMSWOJqU8pwstKVNqfUqJLJmlGmolpd+ktGSeyaZo3gWkFrMBThgEEYIWwlGKDZXgbQQbxl4ASRZMRUHn18EaEGwRirERBSDI02RghUA0G0YhMzipzIWRgJZAcB4Gz8es8xhgtmOF2bIigByvnQsqZUi5Xj6CzKevM0+uKd5JgJUMNZUzNnbL2fzTs1KylggqScrSDKYkaXOldG6GA7obQ+j3AVNBCDyMUYCZREILQxD5H3Llhs8WWwNUSqZyT9Xv0BEKRoYAQgoyAA)

Something else:
Let's say a property is of type `number | null` while `null` is the default value. How does `component-register` even know how to convert the attribute value (string) "100"?
Shouldn't there be an (at least optional) parameter `type` in `PropDefinition`?

```ts
// I simplify a bit, the final type definition more complicated,
// but I guess it should be clear what I mean
interface PropDefinition<...> {
  type: StringConstructor | NumberConstructor | BooleanConstructor | PropConverter<...>
  value: ...
  attribute: string
  notify: boolean
} 

interface PropConverter<T> {
  convertToString(value: T): string,
  convertFromString(value: string): T  
}
```

**Comment by ryansolid** [comment]
Yeah I see.. this problem is 100% Solid's doing not the Web Component library. The spread operator in specific that is causing the problem. I never used it the way you are trying to so I never hit this. If you use the elements directly in the JSX you would have never hit this since strings will be assigned directly to attributes through cloning (like the innerHTML example). And the attributes -> props knows how to handle things. And then everything else being handle as props would be consistent. Only your first example would fail. Admittedly it would have worked a few versions back but it was requested from by a vocal community member to fail in that case to preserve HTMLness.. 

So the weirdness is that with Solid always looks like attributes but always assigning props. So a string is a string. I don't do any processing on property setting. If you changed your toy example 1 to:
```js
render(<Counter initialCount="100" />, '#app1')
```
That is effectively what example 2 in Solid is doing. And fails in the same way.

So let's think of what is reasonable to do here. I could fix example 1. Just let casing pass through. It doesn't allow full HTML semantics which are case insensitive. Solid is case insensitive everywhere else when dealing with native elements. Mind you I'm not sure it's a deal breaker. Case 2 is hard.. the spread would need to make a decision based on value being set at runtime. Internally I can't tell if you are setting it like `value={"..."}` or `value="..."` so the decision to treat them always as props will always interfere here.. THe only thing I can think of is always set strings in spreads on custom elements as attributes.

**Comment by mcjazzyfunky** [comment]
Guess I was wrong.
In the demo we have four cases:

  1. `render(<Counter initialCount={100} />, '#app1')` // not working
  2. `render(<Counter initial-count="100" />, '#app2')` // not working
  3. `render(<Counter initial-count={100} />, '#app3')` // working
  4. `document.querySelector('#app4')!.innerHTML =
        '<my-counter initial-count="100"></my-counter>'` // working

Cases 2 and 3 are actually programming errors (even if TS does not complain, due to the hyphen in `initial-count`), as the "C" in `Counter` is upper-case you should always use the real prop names not the corresponding attribute names. So I guess: No problem that case 2 is not working.

But if case 1 did work that would be really great.
Would it mean that `<my-counter initialCount={100}/>` would also work (which would equally be needed)?

But currently I'm using this just for fun and studying purposes ... really no urgency :wink:
Thanks a lot.

**Comment by ryansolid** [comment]
The thing is in Solid capital letter components are just function calls. So they don't really do anything but pass props through. So passing dash-case through isn't a problem. We treat all things web components as properties generally except static literal values that are compiler analyzable. So spreads or props from above can't be analyzed so they are always treated as properties.

**Comment by ryansolid** [comment]
I was thinking about this more and Solid really doesn't do the property setting thing with camelCase outside of supporting `className` and `htmlFor` for React compat, and the `innerHTML`, `innerText`, and `textContent` trio for setting internal content. Everything else is case insensitive like HTML. There is nothing to say Components need to use camelCase or not.. generally you wouldn't use dash case because it's a pain to access props in JavaScript but nothing stops you.

So passing camelCase through as properties in just this case is inconsistent as it weird for case to suddenly matter. Although webcomponents setting properties in itself is inconsistent. But since Components do nothing themselves the transformation isn't going to happen there. I'm tempted to just rewrite your wrapper in define to do the transformation since this is really brought about due to the pattern you are using.

In any case you should be able to use something like this in the interim pending any decision here.

```js
import { spread } from "solid-js/web";

function transformProps(props) {
   const keys = Object.keys(props);
   const decls = Object.getOwnPropertyDescriptors(props);
   const clone = {};
   for (let i = 0 ; i < keys.length; i++) {
     const k = keys[i];
     const transformed = toKebabCase(k) ;
     Object.defineProperty(clone, transformed, decls[k]) 
   }
   return clone;
}

function toKebabCase(s) { return s.replace(/[A-Z]/g, '-$&').toLowerCase() }

function define(...args) {
  const CustomElement = customElement(...args);
  return (props) => {
    const el = new CustomElement(); // could also be document.createElement(args[0]);
    spread(el, transformProps(props));
    return el;
  }
}
```

**Comment by mcjazzyfunky** [comment]
Thanks, Ryan, the interim solution that you've presented above is working.
Like said in my above examples two cases were actually programming errors on my side, so I will ignore those two cases.
Relevant cases are (it's not surprising that the second case is not working, as it is not effected by the above interim solution):

`<Counter initialCount={100} />` => working
`<my-counter initialCount={100} />` => NOT WORKING!!!! Prop `initialCount` will be ignored.
`<my-counter initial-count="100" />` => working
`<my-counter initial-count={100} />` => working
`elem.innerHTML = '<my-counter initial-count="100" ></my-counter>'` => working

**Comment by ryansolid** [comment]
Yeah I think that is the most consistent outcome with my current thinking the new second case working that way is inconsistent with what I've been building here. I need to review with some others whether we should make a change but that might take a while or never so I wanted to make sure you had a way to take this.

In my opinion the 3rd case in your original example is not a bug and it is working.. and in my opinion working as intended.
`render(<Counter initial-count={100} />, '#app3')` // working
But I agree about the 2nd case in that original one. 

To elaborate further.. picture you had an `aria-label` you want to pass down to a styled component. You'd do this.
```jsx
<StyledButton aria-label="my-button" />
```
I'm not going to arbitrarily support ariaLabel or something. All of this mapping is sort of ridiculous. And although React set some precedence here you will see most newer JSX libraries have strayed from it. I think we shouldn't view our JSX conventions as needing to be the same as this sort of details are not spec. I'd rather users for SVG use `xlink:href` than having to transform some random `xlinkHref` property I make up. When in doubt the safest bet is mimic HTML. It ends up being more consistent that way. I'd view any Component acting as a native proxy like your Web Components or Styled Components perfectly fine to be treated props-wise like their native counterpart. Otherwise you are just incurring extra lookups and potential cost unnecessarily in the majority of cases.
