### ISSUE TITLE
createSelector can't be used more that once for each key

### ISSUE THREAD

**Issue by Freak613** [ryansolid/solid#375]
**Describe the bug**
When checking implementation of `createSelector` I noticed that it does not allow calling selector with same key from multiple computations. Each next listener going to overwrite previous:
https://github.com/ryansolid/solid/blob/master/packages/solid/src/reactive/signal.ts#L222

It is either a bug or it has some undocumented behavior.
From documentation it looks like it supposed to work like simple parameterized selector, without limitation on dependencies.

**To Reproduce**
Create component, that creates selector using `createSelector` and call it few times with same key in computations in the component body or template.

**Expected behavior**
When condition changes for some key, selector signal should notify each listener subscribed to this key.

**Actual behavior**
It's going to notify only last caller.

**Comment by ryansolid** [comment]
Yeah, this probably should be changed. I was meaning to look into the best way to do this, but got sidetracked at some point. There was a discussion in the discord that the current behavior was fine, but I am leaning to towards it to being a bug. Thanks for reporting.

**Comment by Freak613** [comment]
@ryansolid Thanks, that was fast!

But thinking about it further, what if you have condition in memo? Selector doesn't link itself back to current Listener, which means if condition inside memo changed so subscription of selector to memo expected to be disposed, but in fact it will keep updating this memo despite no actual dependency of it.

Actually, replicating whole signal logic inside this helper leads to question what does it provides on top of simple inline source signal call? Store subscriptions by id, but for what? Does iterating over Map somehow more optimized than iterating over signal subscriptions?

**Comment by ryansolid** [comment]
Thanks I see my bug.. I should be caching the local value of Listener. When cleanup runs it will be the parent. Since using the benchmark to test only had a length of 1 it always disposed. Every time a computation is disposed or re-runs it calls the cleanup function. And then recreates it again, so conditionals should work.

Putting a signal on the model(ie.. `isSelected`) is basically the same but you aren't always able to do so, for instance if the data model is shared. This projection basically achieves the same thing. It is significantly faster to go through each item it turns out than to re-eval every row's computations. Worth trying it as a signal though.

**Comment by Freak613** [comment]
Got it. Then it should work properly.

Actually I didn't mean attaching it to model, I meant something like this:
```js
class={memo(selected() === item.id) ? "danger" : null}
// OR
class={memo(() => selected() === item.id ? "danger" : null)}
```
But that was before I noticed that it does early skip of unnecessary component checking.

**Comment by ryansolid** [comment]
Yeah. That is what Michel Westrate suggested when I was trying to make a version for my MobX JSX library but it ended up being slower than doing nothing. Still this conversation gives me an idea on how to implement it there now.
