### ISSUE TITLE
Compile error on using custom directive in child elements

### ISSUE THREAD

**Issue by kfrp** [ryansolid/solid#377]
**Describe the bug**

Compile error on using custom directives in child elements:
``[!] (plugin babel) TypeError: ...\src\App.js: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefined``

If I declare a basic directive function and then try to use it, it does not work in cases where the element on which it is declared is not the top-level element in the component.

So, this works:
```
function Component() {
  return (
    <div use:draggable>
      <h1>...</h1>
      <p>...</p>
    </div>
  );
}
```
but this does not work:
```
function Component() {
  return (
    <div>
      <h1>...</h1>
      <p use:draggable>...</p>
    </div>
  );
}
```

**To Reproduce**
You can clone https://github.com/kfrp/temp-repo as a minimal repo to see the error.  It uses v0.24.13 of both solid-js and babel-preset-solid, but updating solid-js to the latest version also yields the same bug.

I'm just figuring out the ropes and am using `ref` successfully instead, but this seems like unintended behavior, or maybe I'm missing something obvious.

**Comment by ryansolid** [comment]
Yeah found the bug. I do some traversal pruning that was looking for expressions `{ }`. `use:___` is the only boolean attribute that isn't static, so I was missing that case.

Fixed in latest version of the babel plugin (0.25.16). I will update the preset when I do next Solid release. In meanwhile wiping package-lock and removing modules before re-install should be sufficient to get the newest version. Let me know if you have any issues
