### ISSUE TITLE
Children as data?

### ISSUE THREAD

**Issue by bluenote10** [ryansolid/solid#38]
To my knowledge, JSX allows to pass children as data in general. For instance, in React (to my knowledge) this code

```js
return (
  <MyComponent>
    {1}
    {2}
    {3}
  </MyComponent>
);
```

would pass the array `[1, 2, 3]` into the `children` prop of `MyComponent`. Accordingly TypeScript seems to infer the type of `children` by finding the common base type of the children expression and wraps it into an array. 

Currently, this disagrees with Solid's implementation of passing `children`, because it converts everything to a document fragment. This can be quite confusing, because according to the compiler the type of `children` must be an array, but it cannot be used as such, and it might be a gotcha for React users who are used to passing e.g. functions as children.

**Comment by ryansolid** [comment]
It won't convert a single expression to a Document Fragment. I do it to shortcut what I consider the common case. Originally I had the children as arrays but an array of nodes is less efficient as far as my benchmarking shows. I wondered about this precise case but since I had never actually hit it ever using React and the benefits for shortcutting the renderer beneficial I went that way. The main reason is I create nodes by cloning templates. An array would take an otherwise singular template and split it into multiple templates that'd all be cloned separately.

Consider:
```jsx
<MyComponent>
  <div>Hello</div>
  <div>World</div>
</MyComponent>
```
To get the single node effect I would need to write it as:
```jsx
<MyComponent>{
  <>
    <div>Hello</div>
    <div>World</div>
  </>
}</MyComponent>
```

Whereas for the Data Array you can just write:
```jsx
<MyComponent>{
  [1, 2, 3]
}</MyComponent>
```

It's quite possible the types are incorrect. I am yet to use the JSX types in a project and I made the change to the child operation around the same time the types were contributed. What should be happening is any single expression is left untouched to handle (passing data, render props etc) and anything with multiple children is made into a document fragment. That way children is always a single non-array value (unless you pass an array), that can be either used directly or appended to the DOM without further consideration.

**Comment by bluenote10** [comment]
:+1: the single array argument example solves this use case in my opinion.

The only question is if fixing the types is actually possible. It might be part of the JSX language specs requiring that multiple arguments become an array. Even if it's not possible to fix the type it might be enough to just document it as a small deviation from the JSX specs (with a hint that type casts are required in TS).

**Comment by ryansolid** [comment]
We do set up our own types so maybe there is something to be done there?

https://github.com/ryansolid/babel-plugin-jsx-dom-expressions/blob/master/types/index.d.ts

Is it that these types only extend to Intrinsic Elements? And not Custom Elements? I guess this is my TypeScript issue of the week. Can't seem to go a week without finding some new fun surprise.

Help would be very much appreciated to know whether this is a TypeScript solution for this.

**Comment by ryansolid** [comment]
https://github.com/Microsoft/TypeScript/issues/30918 is sort of the opposite issue. Looks like TypeScript won't play ball. I've updated documentation. Seems like that is all I can do.
