### ISSUE TITLE
undefined key in classList

### ISSUE THREAD

**Issue by MrFoxPro** [ryansolid/solid#404]
**Describe the bug**
```jsx
   <el classList={{
        [someMemo()]: true
      }} />
``` 
produces dom element `<el class="undefined"></el>` and not disappears if someMemo() set to non-undefined value
**Expected behavior**
should produce `<el></el>` or error.

**Reproduction**
https://codesandbox.io/s/solid-classlist-6d3mt?file=/index.tsx

**Comment by ryansolid** [comment]
Yeah probably should be skipped. Ie.. `<el></el>` Thanks.

**Comment by MrFoxPro** [comment]
Found out that problem not only with undefined, but any value tat provided as class in `classList`.

**Comment by ryansolid** [comment]
Yeah I never added the negative diff loop. We do have all the information we need for it though as we pass the previous value in. It adds a nice chunk more code. I should do that though now that I've optimized the simple case. I honestly didn't consider these cases initially which is why I thought we could get away with `class:name` as a namespace. Simplifies things greatly, but given how common this is I think it's worth the heavier lifting.

**Comment by ryansolid** [comment]
undefined is weird.. in that any value here is coerced to a string. So checking takes literally checking against "undefined".  I did have a check for empty string. I guess the extra check is cheap enough.

Honestly I didn't even think of using it that way with tracking computed keys, but I can make it work.
