### ISSUE TITLE
Storybook for solid

### ISSUE THREAD

**Issue by atfzl** [ryansolid/solid#69]
Just FYI, It is possible to use [storybook](https://storybook.js.org) with solid just by using [storybook/html](https://storybook.js.org/docs/guides/guide-html/). I have implemented storybook in https://github.com/atfzl/solid-ts-starter.

We can add guide to add storybook for solid projects.

@ryansolid need your help here, where do i need to use `createRoot` while defining my stories in storybook, like in this case: [storybook for counter](https://github.com/atfzl/solid-ts-starter/blob/3bc5533e0f60b112a25c293156e724ac1620cd89/%23/components/counter/counter.stories.tsx)

**Comment by ryansolid** [comment]
That's great. I'd briefly looked at it but hadn't really had the chance to put anything together. `createRoot`  has to synchronously wrap your top level component. Since it looks like you aren't responsible for inserting into the DOM I imagine it would be just around <Counter />. I suppose that is tedious for each method.

```jsx
storiesOf('Counter', module).add('default', () => createRoot(() => <Counter />));
```
We might be able to wrap the whole thing but memory would never be released between stories.
```jsx
createRoot(() => storiesOf('Counter', module).add('default', () => <Counter />));
```

So I just looked at the React internals. And sure enough, there is a way to inject the render function to properly handle memory release. Given each branch is separate nesting the createRoot as I wrote first might be fine.  Let's see if that works I suppose and go from there. We could eventually make something like React does and that could be for the best. But if the simple setup works that's a decent win for now.

**Comment by atfzl** [comment]
Thanks @ryansolid 
```js
storiesOf('Counter', module).add('default', () => createRoot(() => <Counter />));
```
is working !!!

I have moved the repeating createRoot to addDecorator in storybook config: https://github.com/atfzl/solid-ts-starter/commit/4464e911e0bd0db28160574d0a137f324126f0fa and now there is no need for adding createRoot in every story.

It works flawlessly now. Should I add a guide for setting up storybook ?

**Comment by ryansolid** [comment]
Yeah that sounds good. I'm sure others would find that useful.

**Comment by ryansolid** [comment]
I will consider this one closed too. Thank you so much.
