### ISSUE TITLE
What's the `_state` proxy trap helper for?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#7]
https://github.com/ryansolid/solid/blob/de578778fbc6333981c0a67c366314ec3c4ce667/src/State.js#L81

What's that for?

**Comment by ryansolid** [comment]
Proxies for the same object are not equal. Sometime you need to unwrap the proxies to get to the underlying object, usually for equivalency checks. There is no standard way of doing it so I adopted a convention. It could really be named anything. I just needed a way to consistently get to it.

**Comment by trusktr** [comment]
Sounds nice! Can you briefly explain how the API changes affect a user? Or is it all the same on the outside?

**Comment by ryansolid** [comment]
I've changed a lot with 0.3.x. But the changes I'm referring to here was in 0.2.x. I used to (< 0.2.x) only selectively wrap with Proxies. I initially realized with a set function based API I didn't need to be working on the proxy objects outside of Computations (to track deps). In pre 0.1.x this was a huge deal since I used Proxies from the root so the state methods (like set/repace/select) were taking a hit on retrieval along with any dependencies. In 0.1.x I made the State object not use a Proxy and dedicated getter/setters so that stopped being an issue.

Furthermore, one of the awkwardness with Proxies is that when you set new values you don't want to nest Proxies in Proxies. You end up in this inception case where getting a property triggers multiple getters. Most of the time sets happen in action handlers which aren't wrapped so feeding previous state values into themselves (incrementing, clones and mutations) are actually a lot cheaper since you don't need to unwrap. I built in minimal unwrapping (single level) everything optimizing for this case including list reconciliation. At first since this handle the 90% case it seemed reasonable to enforce. And in other cases where you needed equivalency I exposed an isEqual method that could tell if the Objects were equal whether they were the Proxy or the original.

The truth was the scenarios were too narrow and it forced me to write stuff in a very specific way to handle Proxies. So with 0.2.x I made it always wrap and always deep unwrap on set. So as you can imagine considerable performance hit at first. But I actually realized that wrap and unwrap were not optimized and it wasn't as big of a hit in most cases as I expected. So once I always wrapped I needed to make sure it always returned the same Proxy for the same object so equivalency worked, but generally there is no need for application code to do anything but treat it like a normal (albeit immutable object). So if anything it simplifies stuff on the outside since in all cases state.user will equal state.user. So now it is compatible for anything written for S. Like S-Array methods now work.

Ironically after doing this in 0.2.x that increased compatibility, conversely in 0.3.x I've taken a much more directed view on signals. The summary is enforcing Read/Write segregation. Typical Signal API differs reads and writes on whether the method has an argument. Using Array spreads inspired by React Hooks proposal using a similar separation of Read/Write methods. It is surprisingly clean in there is no confusion on what's settable or not and you can control mutability by what methods you pass along. Take a look at the updated examples on Signals. This separation has allowed the State objects being only Proxy from the root again which has led to additional simplification and reduction in the code.  All this moved to less magic and more explicitness.
