### ISSUE TITLE
Dynamic Component support?

### ISSUE THREAD

**Issue by coderbuzz** [ryansolid/solid#73]
`<svelte:component>` like tag to render component dynamically (without Switch)

https://svelte.dev/docs#svelte_component

**Comment by ryansolid** [comment]
Hmm.. haven't thought about this one at all really but let's see if we can make this. The way Solid works is that with the general primitives you should be able to make whatever you want.

First Level, all Components are just functions. So if this is a matter of a downstream condition or something that doesn't update dynamical you can just:
```jsx
let SelectedComponent = state.selected.component
return <SelectedComponent someProp={(state.selected)} />
```
Or look it up from a lookup table etc. But I'm going to assume that is not the case.

So we want a Switcher Component. Maybe something like this:
```jsx
<Switcher component={( state.selected.component )} someProp={(state.selected)} />
```

So I think we could write that like:
```jsx
function Switcher(props) {
  return createMemo(() => {
    const SelectedComponent = props.component;
    return SelectedComponent && SelectedComponent(props);
  })
}
```
This is just a first draft but take a look at an example here. What I did actually was check the prop propagation by passing the swap button as props.  https://codesandbox.io/s/solid-switcher-qhmsn

Does this make sense?

**Comment by coderbuzz** [comment]
I'm trying to make it simpler by utilize state but it seems not working, a function state's value is not "reacted"?

``` javascript
function Component(props) {
    return createMemo(() => {
        const SelectedComponent = props.Class;
        return SelectedComponent && sample(() => SelectedComponent(props));
    });
}

const App = () => {
    const [state, setState] = createState({
        Class: ComponentA,
    });

    return (
        <>
            <Component Class={(state.Class)}></Component>

            <button onClick={() =>
                setState({
                    Class: ComponentB
                })
            }>Swap</button>
        </>
    )
}
```

**Comment by coderbuzz** [comment]
The use case was render a list of components by string class name;
API maybe like this:

```javascript
const ComponentRegistry = [
  ComponentA,
  ComponentB,
]

const data = [
  { name: '  ComponentA', props: {} },
  { name: '  ComponentB', props: {} }
]

...
state.list = data

...
<For each={(state.list)} fallback={(<div>Loading...</div>)}> { item =>
  <Component Class={ ComponentRegistry[item.name] } />
}</For>
```

**Comment by coderbuzz** [comment]
Fortunately I'm able to get the expected behavior by using **h** helper

```javascript
<For each={(state.list)} fallback={(<div>Loading...</div>)}> { item =>
  { h(ComponentRegistry[item.name], item.props) }
}</For>
```

Glad to know if there is a more elegant way 😁

**Comment by ryansolid** [comment]
Ok, yeah. I need to change that. At some point way back to reduce the overhead of native methods I stopped tracking functions. I think that it's inconsistent I will change that. It's a one-liner.

As for your example, I think there are a few things going on. Although it could just be shorthand. I think you just forgot the inner parens (although that shouldn't be necessary for initial render), the registry should be an object. It should be:

```jsx
const ComponentRegistry = {
  ComponentA,
  ComponentB,
}

const data = [
  { name: 'ComponentA', props: {} },
  { name: 'ComponentB', props: {} }
]

...
const [state] = createState({ list: data })

...
<For each={(state.list)} fallback={(<div>Loading...</div>)}> { item =>
  <Component Class={( ComponentRegistry[item.name] )} {...(item.props)} />
}</For>
```
See: https://codesandbox.io/s/solid-switcher-2-g5c7t

Although for your case are you changing it dynamically? If not the following should be the equivalent of the `h` function:
```jsx
<For each={(state.list)} fallback={(<div>Loading...</div>)}> { item => {
  const Component = ComponentRegistry[item.name];
  return <Component {...(item.props)} />
}}</For>
```
The Switcher is only necessary if you intend item.name to change.

**Comment by coderbuzz** [comment]
Nice sample!

The list can be changed dynamically depend on async fetch for example

If the instance has been created the item.name should not changes I think, but if that happen it should destroy and create a new one

What is the proper way if name never changed?

**Comment by ryansolid** [comment]
If the name will never change the Switcher Component is completely unnecessary. If you want to obscure it in a Component to encapsulate you could remove the memo and sample:
```js
function Switcher(props) {
    const SelectedComponent = props.component;
    return SelectedComponent && SelectedComponent(props);
}
```
Basically Components are just functions. So if it looks too messy. Wrap it up.

**Comment by coderbuzz** [comment]
Great! Finally the following mimics Svelte's `<svelte:component>`

```javascript
function Component(props) {
    const SelectedComponent = props.Class;
    return SelectedComponent && SelectedComponent(props);
}

return <For each={( state.list )}>{item =>
    <Component Class={( ComponentRegistry[item.name] )} {...item.props} />
  }</For>
```

Dynamic Component very useful for example routing, load many pages dynamically (without Switch) from another module / class. People who see this feature will get an idea of how to implement a single page application with easy.

Love to have this as a Solid's built-in feature 😁

**Comment by ryansolid** [comment]
Do you have something against `<Switch />`? The children `<Match/>` can also be generated iteratively from data.  I guess it's my React background where routing generally looks like Switch.

I mean this approach is fine but with a JavaScript DSL, it is fairly trivial to write in 2 lines. Essentially we ended wrapping my first suggestion. The 'dirty' solution is fairly common for simple things like passing in template components to children (not so much for routing). A dynamic version is more interesting since I think it could be made to preserves children. Picture swapping out a Container Component that swaps between a panel and modal without destroying and recreating the children. Maybe not common and could handled without changing the Component hierarchy, but unique to this sort of Component.

Anyway, while it's a candidate for control flow inclusion, I feel the verdicts still out for now.

**Comment by coderbuzz** [comment]
No I haven't, but for this case in my opinion Switch Match is not best, too verbose.
Or I'm missed some docs? This one I found.

```javascript
<Suspense fallback={( <Loader /> )} maxDuration={ 500 }>
  <Switch transform={ awaitSuspense }>
    <Match when={( state.tab === 0 )}>
      <AsyncChild page='Uno' />
    </Match>
    <Match when={( state.tab === 1 )}>
      <AsyncChild page='Dos' />
    </Match>
    <Match when={( state.tab === 2 )}>
      <AsyncChild page='Tres' />
    </Match>
  </Switch>
</Suspense>
```

Or can you give me a sample in this case using Switch Match?

**Comment by ryansolid** [comment]
Well your case was just iterating over different templates and in itself isn't routing. There is no condition just template mapping. For custom templating what was done makes a lot of sense. You can build routing on top of that if you wish by pushing the conditionals into the children (essentially build your own Switch). You could also do routing with that Component switching approach much like the first sandbox and just switch between selected components. But you'd be making the list of possible routes and condition resolution elsewhere (developing whatever DSL makes sense) which is perfectly fine. 

It's pretty common in dynamic nested routing libraries to work more like Switch. Especially in React land. For example:
[React Router](https://reacttraining.com/react-router/web/guides/quick-start)
[Reach Router](https://reach.tech/router)
[Svelte Routing](https://github.com/EmilTholin/svelte-routing)
[Polymer App Route](https://github.com/PolymerElements/app-route)

I think there are several ways to approach this and I know there is some aversion to putting something like Route resolution in JSX. I did have that at one point. My own [WebComponent Router](https://github.com/ryansolid/webcomponent-router#readme) works more like [Vue](https://github.com/vuejs/vue-router) or [Ember Router](https://guides.emberjs.com/release/routing/defining-your-routes/). And this is a good approach to take something like what we have built in this thread and have it read off a Context API store that its Provider wraps your app with. A pretty slick Router could be the output.

As a library author something like Switch is appealing because it's so dirt simple. As a primitive it handle a lot of different cases (including routing) very easily but doesn't prevent people from developing more advanced routing mechanisms. I can build a simple router with path resolution: https://codesandbox.io/s/jjp8m8nlz5. A handful of lines of code I've built a single layer router based on hashchange. Or in the other example a simple tab switcher. I'm sure there are better Routing options out there for Solid but I will leave that for the community as I'm sure they will have a good idea exactly what they are looking for that week, and it feels like opinions like this change weekly. I know mine do.

I was just interested what about Switch put you off right off the start since I do like the basic primitives to at least feel inviting if only a little basic. If it's just the verbosity, that's fine. I'm always interested in feedback.

**Comment by ryansolid** [comment]
I'm going to leave this as is for now. I do see some value here. However, its very standard JSX stuff. Stuff I realize that isn't obvious if you haven't used JSX or React before. Maybe I need to work on better examples. But I don't see the need to include this as part of core currently.
