### ISSUE TITLE
Expression not being triggered when using native functions on arrays

### ISSUE THREAD

**Issue by atfzl** [ryansolid/solid#78]
Modified Counter Example: https://codesandbox.io/s/solid-simple-todos-fv0zi

The style of this line does not update when state.todos change
```js
<div style={(state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'})}>
   All Checked
</div>
```

**Comment by atfzl** [comment]
It works when i enclose the jsx in a function.

```js
{() => <div style={(state.todos).every(todo => todo.done) ? {} : {textDecoration: 'line-through'}}>
        All Checked
      </div>}
```

Also i have a doubt.
should i enclose the complete expression or just the state

```js
(state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'})
```

OR

```js
(state.todos).every(todo => todo.done) ? {} : {textDecoration: 'line-through'}
```

**Comment by ryansolid** [comment]
It is highly likely this has to do with `style` specifically.

You wrap the whole expression. The reason wrapping in a function works is it is the same as wrapping in parens. So it is enclosing the div creation as well. Since the inner binding is no longer being wrapped (wrapping just state doesn't do anything) the parent is tracking.

This is why I'm thinking something is wrong with `style` specifically since the outer context tracks fine. I'll take a look a bit later.

**Comment by atfzl** [comment]
Hmmm, so the styles are being merged, i tested it here: https://codesandbox.io/s/solid-simple-todos-ncpff

The `color: red` property stays after the condition changes

```js
(state.todos.every(todo => todo.done) ? { textDecoration: 'none' } : { textDecoration: 'line-through', color: 'red' } )
```

But isn't this behaviour conflicting with the way react does things.
It tried in React and the styles are not merged there. See: https://codesandbox.io/s/sad-snyder-8efgw

**Comment by atfzl** [comment]
> The reason wrapping in a function works is it is the same as wrapping in parens. So it is enclosing the div creation as well. Since the inner binding is no longer being wrapped (wrapping just state doesn't do anything) the parent is tracking.

So when using native elements, they are tracked normally.
But if we want to use custom components, we have to wrap them in functions.

Is this what you are saying ?
https://codesandbox.io/s/solid-counter-2netg

```js
    <div>
      <div>Element: </div>
      <div>{( state.flag ? 'true' : 'false' )}</div>
    </div>
    <div>
      <div>Component:</div>
      <Component>{( state.flag ? 'true' : 'false' )}</Component>
    </div>
```

Here the Component's children does not update on state change, but element's children updates normally.

Wrapping the `<Component>` call in function fixes this.

```js
    <div>
      <div>Component:</div>
      {() => <Component>{( state.flag ? 'true' : 'false' )}</Component>}
    </div>
```

The other way Component is being updated is if i add any string before the dynamic children.
Why does this work ?
```js
<Component>flag: {( state.flag ? 'true' : 'false' )}</Component>
```

**Comment by ryansolid** [comment]
> But isn't this behaviour conflicting with the way react does things.

Definitely. That is what I was saying. Having used Fine Grained libraries way before React ever came into existence it had never occurred to me to do it any different in my React code, even though it is completely legal. If you look at Knockout, Svelte, Ember, Ractive, Surplus, etc.. they are all effectively do merge. But that is also because their syntax doesn't allow passing in an object. JSX (or even HyperScript/Tagged Literals) + Fine Grained is a newer area. 

All I was saying is a Virtual DOM library (like React, or Vue) already has diffing ability at it's disposal, so it's pretty trivial (they also have the previous iteration of the Virtual DOM to compare against), where as for the techniques Solid uses it's unprecedented. Performance of styles is very critical since people use these to do animations. The routine Inferno does seems acceptable. It just adds overhead for everyone.

I'm just unclear how much of an edge case this pattern is. Since it's legal it's probably common enough. My first impulse to keep it fast and simple. But greater React compatibility is probably worth consideration. I do like these issues are coming up. It pushes me to solve problems that many of the similar libraries haven't had a chance to yet.

> So when using native elements, they are tracked normally.
But if we want to use custom components, we have to wrap them in functions.

No that isn't what I was saying.  Your example doesn't work because you didn't wrap the props.children dynamically inside your Component. Your component should be:
```jsx
function Component(props) {
  /* prettier-ignore */
  return <div>{(props.children)}</div>;
}
```

Although I understand why it may have updated at various points which has led to confusion. One of the reasons I'm so explicit is it is very easy with fine-grained to re-render your whole view inefficiently and not notice it at first. It might be easiest to psuedo code(my actual code uses template cloning, but point holds) the generated code to understand what I'm saying with your original example.

```jsx
const el = <div style={(state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'})}>
   All Checked
</div>

// roughly compiles to
const el = document.createElement('div');
el.textContent = 'All Checked';
createEffect(() => Object.assign(el.style, (state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'}));
```
As you can see we create an effect that triggers on state.todos, and todo.done changes merges. Whereas your second example "works" is:
```jsx
{() => <div style={(state.todos).every(todo => todo.done) ? {} : {textDecoration: 'line-through'}}>
  All Checked
</div>}

// is equivalent to
{(<div style={state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'}}>
  All Checked
</div>)}

// roughly compiles to
createEffect(() => {
  const el = document.createElement('div');
  el.textContent = 'All Checked';
  Object.assign(el.style, (state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'});
});
```
As you see this time the whole thing is inside an effect so every time state.todos or todo.done updates it recreates the parent div and sets the styles for the first time.

Now if you did wrap the inner expression as well you would get back to the original behaviour since it only tracks up to it's immediate parent. The outer effect will never re-evaluate since there are no dynamic properties accessed in its scope.

```jsx
{(<div style={(state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'})}>
  All Checked
</div>)}

// roughly compiles to
createEffect(() => {
  const el = document.createElement('div');
  el.textContent = 'All Checked';
  createEffect(() => Object.assign(el.style, (state.todos.every(todo => todo.done) ? {} : {textDecoration: 'line-through'}));
});
```

Wrapping everything is how Surplus and classically a lot of these libraries work. To avoid this confusion generally I try to keep everything outside of bindings inert(non-tracked). It's why all control flows are sampled. In most cases if something is not updating it's because you are missing a parens at the deepest level (closest) to the data that is being observed, and you do not need to worry about how that might affect upstream rendering.

I find this explicitness logical in most cases as it cuts off people trying to do things that would cause weird behaviour. Your first assumption of how everything should work from a wrapping perspective was correct. It was just that because the style binding wasn't working as expected that you ended up trying other things that stumbled into this. Hopefully you don't mind my terribly in depth explanation.

**Comment by atfzl** [comment]
@ryansolid Really appreciate the effort you put into explaining this. In depth explanations is what I needed. Thank you 💯

My actual problem was something else which I am understanding after all your explanations.
My problematic code was something like this: https://codesandbox.io/s/solid-counter-j3xie

```js
import { css } from "emotion";

function Component(props) {
  return (
    <div
      className={css`
        background-color: ${(() => {
          switch ((void 0, props.flag)) {
            case true:
              return "blue";
            case false:
              return "red";
            default:
              return "transparent";
          }
        })()};
      `}
    >
      {(void 0, props.children ? "true" : "false")}
    </div>
  );
}

export default Component;
```

**Note:** I am using `void 0` so that prettier does not remove it.

My components style generated by emotion wasn't changing on the basis of condition.
Changing the above code to following fixed the problem.

```js
import { css } from "emotion";

function Component(props) {
  return (
    <div
      className={
        (void 0,
        css`
          background-color: ${(() => {
            switch (props.flag) {
              case true:
                return "blue";
              case false:
                return "red";
              default:
                return "transparent";
            }
          })()};
        `)
      }
    >
      {(void 0, props.children ? "true" : "false")}
    </div>
  );
}

export default Component;
```

I needed to wrap the complete expression for className attribute in `()`.

But the strange thing is the first code was working for some cases.
