### ISSUE TITLE
How do accessors work?

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/solid#80]
How do accessors work if they aren’t wrapped in a function like other computations?  Do accessors automatically run when any of their dependent signals change or does that only automatically work for effects and memos?  Accessors aren’t concepts in mobx or s.js right?

**Comment by ryansolid** [comment]
Ok a few quick things. What I refer to as accessors are:
```js
() => ....
```
They are just getter functions or thunks. Argument-less functions that return a value. And more specifically they access reactive (observable data). It's the same basis for patterns in S.js. I just named it.  I make this clarification because I want to differentiate between getters and setters. It is important for Solid's design philosophy to split read from writes. To be fair, there are cases where you might want to package them together and that is fine. It's just not the default. In addition, they are more than just getters since they might contain accessor executions themselves.

The simplest accessor is the getter part of a Signal. Ex.. `s` in this example:
```js
const [s, setS] = createSignal(10);

// this is equivalent to:
const signal = S.data(10).
  s = () => signal(),
  setS = v => signal(v);
```

I use accessors a lot since they are a way to pass State (proxy) access to be evaluated lazily. Ex:
```js
() => state.count
```

However, you can take this a lot farther. If the intermediate states aren't worth memoizing on you can just chain these accessors. Ex...

```js
const [data, setData] = createSignal('John')
   upper = () => data().toUpperCase(),
   reverse = () => upper().reverse();
```
Now on their own these will never update. You need to wrap them in a computation.
```js
const transformed = createMemo(reverse); // or data or upper

// this is equivalent to 
const transformed = S(reverse);
```
My point is that it is wasteful to wrap each in computation in most cases. You only want to cache values that are expensive. You could insert a wrapper at any point but it is probably unnecessary.

Hopefully, that gives you more perspective in how Solid works.

**Comment by mrjjwright** [comment]
Yes this totally helps.  I thought that's what you were doing, formalizing that step.  Yes, the intermediate  computations states definitely are not worth memoizing, just the one for the client.   Using this, going great so far.  A ton of formalization and it looks like (hopefully) testing has gone on since and the documentation is great.  I think I am grokking it all and you have taken the best of React hooks and many other concepts and really synthesized here in a very well solid way, congrats!

**Comment by mrjjwright** [comment]
I am switching over it to my app because it provides a modern, well tested and flexible fine grained signaling and rendering toolkit on which I can build my app.

**Comment by mrjjwright** [comment]
btw, I was enchanted with Mobx boxed observables a couple of years ago and used them to great effect in building an editor for React components for non technical people because they were like worm holes to sideways inject into any part of the hierarchy in React.  Daniel Earwicker in particular showed me how it was done and the power of having simple and different primitives around `set` and `get`, `read` and `write` and practically they were awesome.  But I was never able to understand why they worked so well until you started explaining all this recently.
