### ISSUE TITLE
`className` on svg doesn't transpile to `class`

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#89]
I've got some JSX:

```jsx
      <div className={c.indicator}>
        <svg className={c.indicator}>
```

and in the output DOM I see:

```html
      <div class="some-class">
        <svg className="some-class">
```

Looks like the className doesn't get converted to class on the svg element.

If I tried to work around it by changing it to `class={c.indicator}`, but TypeScript complains that `class` is not a valid property (I have `@types/react` in place, because this is a React project in which I'm incrementally introducing solid-based components).

**Comment by trusktr** [comment]
Alright, I was able to add the `class` attribute type by augmenting the react module:

```ts
declare module 'react' {
  interface SVGAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    class?: string;
  }
}
```

but the output is still

```html
        <svg className="some-class">
```

**Comment by ryansolid** [comment]
Yeah I haven't added any camelcase mapping for SVG attributes since they aren't props. Maybe I should be doing that. React actually went back and forth on it but ultimately landed back on camelCase for SVG. The thinking for not mapping was why handle SVG different than custom elements. Like if you are setting an attribute why not set it as an attribute etc. That decision was reversed though.

**Comment by ryansolid** [comment]
This should be fixed in the latest version. v0.12.0.

**Comment by ryansolid** [comment]
I did it for statics as well in the latest version of the babel plugin v0.13.2.
