### ISSUE TITLE
For rendering

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/solid#98]
I am having an odd issue.  When I use `npm init solid app myApp` and replace App.js with the following:

```
function App() {
  return (
    <div>
      <For each={["a", "b", "c"]}>
        {item => {
          console.log(item);
          return <div>{item}</div>;
        }}
      </For>
    </div>
  );
}

export default App;

```
and run it it doesn't print anything on the screen and logs `undefined` 3 times.  Inside the inspector there are 3 empty divs inside the div container.

When I run this in code sandbox (by modifying one of your examples) it displays `a, b, c` in succession as expected both on the screen and in the console (https://codesandbox.io/s/solid-counter-fkkxe?fontsize=14). 

 I can't figure out what is going on with my local environment.  I am running Solid `0.13.1` and `babel-solid-preset` of `0.2.1` both locally and on code sandbox.  I believe the problem is somehow in the `For` component as just using a simple `map` works as expected.   I noticed in my work project today that when I upgraded to `0.13.1` from `0.12.0` that some of my `For` components stopped rendering.

**Comment by mrjjwright** [comment]
I also tried npm linking directly against master `solid-js` just in case and still am having the same issue.

**Comment by ryansolid** [comment]
Any chance of showing the compiled code output for that part? It might be worth looking at.

Also, weird stuff like this can happen when there are multiple versions of Solid. `For` is coming from "solid-js/dom" which might be the only difference.

**Comment by mrjjwright** [comment]
```javascript
function App() {
  return function () {
    const _el$ = _tmpl$.cloneNode(true);

    Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["insert"])(_el$, Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["For"])({
      each: ["a", "b", "c"],
      children: () => item => {
        console.log(item);
        return function () {
          const _el$2 = _tmpl$.cloneNode(true);

          Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["insert"])(_el$2, item);

          return _el$2;
        }();
      }
    }));

    return _el$;
  }();
}
```

**Comment by mrjjwright** [comment]
Fixed after deleting my package-lock.json as well as node_modules, which I had not tried together, was just deleting node_modules.  So sorry! 


Here was the compiled output after updating `package-lock.json`.  Just to make this a learning experience, can you explain how the `For` component works a bit deeper and what was happening?

```javascript
function App() {
  return function () {
    const _el$ = _tmpl$.cloneNode(true);

    Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["insert"])(_el$, Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["createComponent"])(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["For"], {
      each: ["a", "b", "c"],
      children: () => item => {
        console.log(item);
        return function () {
          const _el$2 = _tmpl$.cloneNode(true);

          Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["insert"])(_el$2, item);

          return _el$2;
        }();
      }
    }, ["children"]));

    return _el$;
  }();
}
```

**Comment by ryansolid** [comment]
The output looks the same. So I guess it was just a version of Solid thing. That there were multiple versions of Solid.

That output does reveal a bug in my heuristic it looks like. It isnt that detrimental but children is being wrapped when it shouldn't.

I don't think `For` itself is that interesting as it is just `mapSample`. But the way Components work might be. They do a bit more than just being a function call. As soon as we detect expressions that need to be wrapped it changes into a `createComponent` call. The first argument is the Component function. The second is the props object with any props that need to be wrapped, wrapped by the compiler. The 3rd is an array of wrapoed keys that need to be converted to object getters on the props object. This all allows props, wrapped or not, to be accessed as simple properties. However they themselves are not computation bindings. By making them getters they become just functions, so effectively we are just deferring access until where you use them. In so the consumer can resolve them inside a computation context or not. Wrapping something accidentally that shouldnt isnt that big of a deal here since it won't act differently but it is a tiny overhead.

**Comment by mrjjwright** [comment]
I didn't even notice the call to `createComponent` but that is super cool and explains that third Array of strings param.   Thanks so much for the explanation!
