### ISSUE TITLE
Move to discord app

### ISSUE THREAD

**Issue by aguilera51284** [ryansolid/solid#99]
Have you considered moving the main chat to discordapp?

there are many advantages to it

**Comment by ryansolid** [comment]
Sure it's come up. Truthfully I just don't have much experience with these apps. Everyone was suggesting Gitter and I went against that and setup Spectrum because it checked all the boxes I was looking for. But then it ended up having horrendous performance issues for non-Chrome browsers. So I ended up setting up Gitter in the end again at the suggestion of people. I've heard good things about Discord. Gitter was just super simple to set up with the Github integration. I'm not opposed setting up a Discord, I just don't want to fracture the small community we have here too much and I haven't felt the limitations of Gitter yet given how small the community is currently. So as always love to hear some more opinions here, as I'm probably not going to look into changing again right away, but I'd love to find the tools that make the most sense.

**Comment by aguilera51284** [comment]
I think it is better discord, for several channels of large tools are there.

**Comment by ryansolid** [comment]
What about Slack? I have created one as a way to communicate with people working on the Solid Site, I could open that up to the Community. Does anyone think that could be a good solution?

I'm just trying to not maintain a ton of different sites.

**Comment by atfzl** [comment]
Yeah Slack seems like a good idea as most people are already accustomed to using Slack at their workplaces.

**Comment by polkovnikov-ph** [comment]
Slack is nice if it's fine to pay for it or get conversation history constantly wiped (for a big server it happens daily).

I second for Discord. It monetizes by selling ability to add more emoji and do screencasts. UI is almost indistinguishable from Slack, so switching shouldn't be a problem.

If you'd like to avoid the painful choice of commercial software with hidden risks, IRC is still the only choice.

**Comment by ddibiase** [comment]
I believe that a lot of dev companies and start-ups use Slack. Is that a correct assumption? If so, it's already installed and used heavily by the extended community.

I actually love Discord (for gaming) and didn't realise there was a push towards it in OSS. My concern is that it hasn't hit critical mass and I'd personally hate having Slack and Discord open at the same time :-/

**Comment by davedbase** [comment]
I spoke with Ryan about this in more detail and given the feedback and some research, Discord is a good place to house our community chat moving forward.

Here's a link you can follow to join the server: https://discord.gg/4pzspd7

We're still getting setup and configuring everything. If you have any suggestions, please mention them! Looking forward to seeing everyone on it.

**Comment by ryansolid** [comment]
Yeah I think this wraps that up. Thanks @aguilera51284 for the suggestion.
